﻿CREATE DATABASE HTBanHang
USE HTBanHang
GO

CREATE TABLE MATHANG
(
	MAMH INT NOT NULL,
	TENMH NVARCHAR(50),
	LOAI INT,
	GIA MONEY,
	SLTTHIEU INT,
	SLTDA INT,
	SLTON INT,
	MANCC INT
	PRIMARY KEY(MAMH)
)

CREATE TABLE LOAI
(
	MALOAI INT NOT NULL,
	TENLOAI NVARCHAR(50),
	PRIMARY KEY(MALOAI)
)

CREATE TABLE NHACUNGCAP
(
	MANCC INT NOT NULL,
	TENNCC NVARCHAR(50)
	PRIMARY KEY(MANCC)
)

CREATE TABLE NHANVIEN
(
	MANV INT NOT NULL,
	MATKHAU VARCHAR(50),
	HOTEN NVARCHAR(50),
	CHUCVU NVARCHAR(50)
	PRIMARY KEY(MANV)
)

CREATE TABLE DONNHAPHANG
(
	MADONNHAP INT NOT NULL,
	NGUOINHAP INT,
	TONGSL INT,
	TONGTIEN MONEY,
	NGAYNHAP DATE,
	LYDO NVARCHAR(50),
	TINHTRANG NVARCHAR(50)
	PRIMARY KEY(MADONNHAP)
)

CREATE TABLE DSNHAPHANG
(
	MADONNHAP INT NOT NULL,
	MAMH INT NOT NULL,
	SL INT,
	MANCC INT
	PRIMARY KEY(MADONNHAP,MAMH)
)

CREATE TABLE DONTRAHANG
(
	MADONTRA INT NOT NULL,
	NGUOILAP INT,
	NGAYLAP DATE,
	TENDOITAC NVARCHAR(50)
	PRIMARY KEY(MADONTRA)
)

CREATE TABLE DSTRAHANG
(
	ID INT NOT NULL,
	MADONTRA INT,
	MAMH INT,
	SL INT,
	LYDO NVARCHAR(50)
	PRIMARY KEY(ID)
)

CREATE TABLE HOADON
(
	MAHD INT NOT NULL,
	SDT VARCHAR(50),
	EMAIL VARCHAR(50),
	DIACHI NVARCHAR(50),
	TONGTIEN MONEY,
	NVBANHANG INT,
	NVGIAOHANG INT,
	MATHE VARCHAR(50), -- Chỉ dành cho KH thanh toán qua thẻ
	XACNHANTHANHTOAN BIT-- 0 là chưa xác nhận, 1 là đã xác nhận
	PRIMARY KEY(MAHD)
)

CREATE TABLE MATHANGLOI
(
	MAHD INT NOT NULL,
	MAMH INT NOT NULL,
	SL INT,
	LYDO NVARCHAR(20)
	PRIMARY KEY(MAHD,MAMH)
)

CREATE TABLE HDTHE
(
	MAHD INT NOT NULL,
	MATHE varchar(50) NOT NULL,
	XACNHAN BIT
	PRIMARY KEY(MAHD,MATHE)
)

CREATE TABLE HD_MH
(
	ID INT NOT NULL,
	MAHD INT NOT NULL,
	MAMH INT NOT NULL,
	SL INT,
	GIA MONEY,
	TRAHANG BIT
	PRIMARY KEY(ID)
)

CREATE TABLE TINNHANQC
(
	NGAYPHAT DATE NOT NULL,
	MAMH INT NOT NULL,
	SDT VARCHAR(50) NOT NULL,
	MANV INT,
	TINHTRANG BIT
	PRIMARY KEY(NGAYPHAT,MAMH,SDT)
)

CREATE TABLE DOITACQC
(
	MADT INT NOT NULL,
	TENDT NVARCHAR(50),
	NGAYKIHD DATE,
	THOIHAN DATE,
	TTVITRI NVARCHAR(50),
	NVDANGTIN INT
	PRIMARY KEY(MADT)
)

CREATE TABLE THONGKECMT
(
	ID INT NOT NULL,
	MAMH INT,
	HOTENKH NVARCHAR(50),
	EMAIL VARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50),
	NOIDUNG NVARCHAR(1000),
	LOAICMT BIT,--Tốt là 1, xấu là 0
	NVTK INT
	PRIMARY KEY(ID)
)

CREATE TABLE DSDEN
(
	STT INT,
	EMAIL VARCHAR(50)
	PRIMARY KEY(STT),
	UNIQUE (EMAIL)
)

/*--Tạo FK
ALTER TABLE MATHANG ADD CONSTRAINT FK_MH_LOAI FOREIGN KEY (LOAI) REFERENCES LOAI(MALOAI)
GO
ALTER TABLE MATHANG ADD CONSTRAINT FK_MH_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
GO

ALTER TABLE DONNHAPHANG ADD CONSTRAINT FK_DNH_NV FOREIGN KEY (NGUOINHAP) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE DSNHAPHANG ADD CONSTRAINT FK_DSNH_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
GO
ALTER TABLE DSNHAPHANG ADD CONSTRAINT FK_DSNH_DNH FOREIGN KEY (MADONNHAP) REFERENCES DONNHAPHANG(MADONNHAP)
GO
ALTER TABLE DSNHAPHANG ADD CONSTRAINT FK_DSNH_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
GO

ALTER TABLE DSTRAHANG ADD CONSTRAINT FK_DSTH_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
GO
ALTER TABLE DSTRAHANG ADD CONSTRAINT FK_DSTH_DTH FOREIGN KEY (MADONTRA) REFERENCES DONTRAHANG(MADONTRA)
GO

ALTER TABLE DONTRAHANG ADD CONSTRAINT FK_DTH_NV FOREIGN KEY (NGUOILAP) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE HOADON ADD CONSTRAINT FK_HD_NVBH FOREIGN KEY (NVBANHANG) REFERENCES NHANVIEN(MANV)
GO
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_NVGH FOREIGN KEY (NVGIAOHANG) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE MATHANGLOI ADD CONSTRAINT FK_MHL_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
GO
ALTER TABLE MATHANGLOI ADD CONSTRAINT FK_MHL_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
GO

ALTER TABLE HDTHE ADD CONSTRAINT FK_HDT_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
GO

ALTER TABLE HD_MH ADD CONSTRAINT FK_HDMH_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
GO
ALTER TABLE HD_MH ADD CONSTRAINT FK_HDMH_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
GO

ALTER TABLE TINNHANQC ADD CONSTRAINT FK_TNQC_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
GO
ALTER TABLE TINNHANQC ADD CONSTRAINT FK_TNQC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE DOITACQC ADD CONSTRAINT FK_DTQC_NV FOREIGN KEY (NVDANGTIN) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE THONGKECMT ADD CONSTRAINT FK_TKCMT_NV FOREIGN KEY (NVTK) REFERENCES NHANVIEN(MANV)
GO
*/