USE HTBanHang
GO

/*----------------------------------NHAN XET MAT HANG----------------------------------*/
--Insert (KH nhận xét, khi bấm gửi thì sẽ insert vào bảng)
CREATE PROC sp_InTKCmt @HOTENKH NVARCHAR(50),@MAMH INT,@EMAIL VARCHAR(50),@DIACHI NVARCHAR(50),@NOIDUNG NVARCHAR(1000)
AS
	IF((NOT EXISTS(SELECT*FROM DSDEN WHERE EMAIL=@EMAIL))AND(EXISTS(SELECT*FROM MATHANG WHERE MAMH=@MAMH)))
	BEGIN
		DECLARE @ID INT
		SET @ID=(SELECT MAX(ID) FROM THONGKECMT)+1
		IF(@ID IS NULL)
			SET @ID=1
		INSERT INTO THONGKECMT VALUES(@ID,@MAMH,@HOTENKH,@EMAIL,@DIACHI,@NOIDUNG,NULL,NULL)
	END
GO

/*----------------------------------DSDEN----------------------------------*/
--INSERT
Create procedure ThemDanhSachDen @Email varchar(50)
as
if(not exists(select * from DSDEN where EMAIL=@Email))
begin
declare @STT int
set @STT=(select max(STT) from DSDEN)
if(@STT is null)
begin
set @STT=1
end
else
begin
set @STT=@STT+1
end
insert into DSDEN values(@STT,@EMAIL)
end

/*---------------------------------- HOADON ----------------------------------*/
--Thêm hoá đơn
create procedure ThemHoaDon @SDT varchar(50),
@email varchar(50),
@diachi nvarchar(50),
@tongtien money,
@mathe varchar(50)
as
declare @MAHD int
set @MAHD=(select max(MAHD) from HOADON)
IF(@MAHD is null)
begin
set @MAHD=1
end
else
begin
set @MAHD=@MAHD+1
end
insert into HOADON values(@MAHD,@SDT,@email,@diachi,@tongtien,null,null,@mathe,null)

--Thêm chi tiết hoá đơn
create procedure ThemChiTietHoaDon @MAHD int,@MAMH int, @sl int, @gia money
as
declare @id int
set @id=(select max(ID) from HD_MH)
if(@id is null)
begin
set @id=1
end
else
begin
set @id=@id+1
end
insert into HD_MH values(@id,@MAHD,@MAMH,@sl,@gia,null)
declare @slton int
set @slton =((select SLTON from MATHANG WHERE MAMH=@MAMH)-@sl)
update MATHANG set SLTON=@slton where MAMH=@MAMH

--store sử dụng select dữ liệu vào combobox
create proc XemNhanVien
as
select HOTEN FROM NHANVIEN WHERE CHUCVU=N'Giao hàng'

--Cập nhật hoá đơn, nvgiao hàng, nv bán hàng
create proc CapNhatHoaDon @MAHD INT, @MANV int, @hoten nvarchar(50)
as
DECLARE @MANVGH INT
SET @MANVGH=(SELECT TOP 1 MANV FROM NHANVIEN where HOTEN=@hoten ORDER BY NEWID())
update HOADON set NVBANHANG=@MANV, NVGIAOHANG=@MANVGH WHERE MAHD=@MAH



/*----------------------------------MATHANG----------------------------------*/
--Insert 
CREATE PROC sp_InMH @TENMH NVARCHAR(50),@LOAI INT,@GIA MONEY,@SLTON INT,@MANCC INT
AS
	IF((EXISTS(SELECT MALOAI FROM LOAI WHERE MALOAI=@LOAI)) AND (EXISTS(SELECT MANCC FROM NHACUNGCAP WHERE MANCC=@MANCC)))
	BEGIN
		DECLARE @MAMH INT=(SELECT MAX(MAMH) FROM MATHANG)+1
		DECLARE @TENLOAI NVARCHAR(50) = (SELECT TENLOAI FROM LOAI WHERE MALOAI=@LOAI)
		DECLARE @SLTTHIEU INT, @SLTDA INT
		IF(@MAMH IS NULL)
			SET @MAMH=1
		IF(@TENLOAI=N'Gia dụng')
		BEGIN	
			SET @SLTTHIEU = 50
			SET @SLTDA = 200
		END 
		ELSE IF(@TENLOAI=N'Thực phẩm' OR @TENLOAI=N'Thực phẩm chức năng' OR @TENLOAI=N'Đồ uống')
		BEGIN	
			SET @SLTTHIEU = 100
			SET @SLTDA = 250
		END 
		ELSE IF(@TENLOAI=N'Điện tử')
		BEGIN	
			SET @SLTTHIEU = 50
			SET @SLTDA = 500
		END 
		ELSE IF(@TENLOAI=N'Hoa' OR @TENLOAI=N'Thú cưng')
		BEGIN	
			SET @SLTTHIEU = 10
			SET @SLTDA = 100
		END 
		ELSE
		BEGIN
			SET @SLTTHIEU = 100
			SET @SLTDA = 300
		END
		IF((@SLTON<=@SLTDA)AND(@SLTON>=@SLTTHIEU))
			INSERT INTO MATHANG VALUES (@MAMH,@TENMH,@LOAI,@GIA,@SLTTHIEU,@SLTDA,@SLTON,@MANCC)
	END
GO

--Update giá mặt hàng 
CREATE PROC sp_UpGia @MAMH INT,@GIA MONEY
AS
	IF((EXISTS(SELECT*FROM MATHANG WHERE MAMH=@MAMH)) AND @GIA>0)
		UPDATE MATHANG SET GIA=@GIA WHERE MAMH=@MAMH
GO

/*----------------------------------LOAI----------------------------------*/
--Insert
CREATE PROC sp_InLoai @TENLOAI NVARCHAR(50)
AS
	IF(NOT EXISTS(SELECT TENLOAI FROM LOAI WHERE TENLOAI=@TENLOAI))
	BEGIN
		DECLARE @MALOAI INT=(SELECT MAX(MALOAI) FROM LOAI)+1
		IF(@MALOAI IS NULL)
			SET @MALOAI=1
		INSERT INTO LOAI VALUES(@MALOAI,@TENLOAI)
	END
GO

--Update tên loại
CREATE PROC sp_UpTenLoai @MALOAI INT,@TENLOAI NVARCHAR(50)
AS
	IF(NOT EXISTS(SELECT TENLOAI FROM LOAI WHERE TENLOAI=@TENLOAI))
		UPDATE LOAI SET TENLOAI=@TENLOAI WHERE MALOAI=@MALOAI
GO

/*---------------------------------- NHACUNGCAP ----------------------------------*/
--Insert
CREATE PROC sp_InNCC @TENNCC NVARCHAR(50)
AS
	IF(NOT EXISTS(SELECT*FROM NHACUNGCAP WHERE TENNCC=@TENNCC))
	BEGIN
		DECLARE @MANCC INT =(SELECT MAX(MANCC) FROM NHACUNGCAP)+1
		IF(@MANCC IS NULL)
			SET @MANCC=1
		INSERT INTO NHACUNGCAP VALUES(@MANCC,@TENNCC)
	END
GO

/*---------------------------------- NHANVIEN ----------------------------------*/
--Insert (Mật khẩu của NV khi mới được thêm vào là MANV của NV đó)
CREATE PROC sp_InNV @HOTEN NVARCHAR(50),@CHUCVU NVARCHAR(50)
AS
	DECLARE @MANV INT =(SELECT MAX(MANV) FROM NHANVIEN)+1
	IF(@MANV IS NULL)
		SET @MANV=1
	INSERT INTO NHANVIEN VALUES(@MANV,@MANV,@HOTEN,@CHUCVU)
GO

--Update mật khẩu
DROP PROC sp_UpMKNV
CREATE PROC sp_UpMKNV @MANV INT,@MATKHAU_CU VARCHAR(50),@MATKHAU_MOI VARCHAR(50)
AS
	IF(EXISTS(SELECT*FROM NHANVIEN WHERE MANV=@MANV AND MATKHAU=@MATKHAU_CU))
		UPDATE NHANVIEN SET MATKHAU=@MATKHAU_MOI WHERE MANV=@MANV
GO

/*----------------------------------DONNHAPHANG----------------------------------*/
--Insert
CREATE PROC sp_InDNH @NGUOINHAP INT,@LYDO NVARCHAR(50)
AS
	IF(EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@NGUOINHAP AND CHUCVU=N'Bán hàng'))
	BEGIN
		DECLARE @MADONNHAP INT=(SELECT MAX(MADONNHAP) FROM DONNHAPHANG)+1
		IF(@MADONNHAP IS NULL)
			SET @MADONNHAP=1
		INSERT INTO DONNHAPHANG VALUES (@MADONNHAP,@NGUOINHAP,0,0,GETDATE(),@LYDO,N'Chờ xác nhận')
	END
GO

--Update Tình trạng
CREATE PROC sp_UpDNH @MADONNHAP INT,@TINHTRANG NVARCHAR(50)
AS
	IF(EXISTS(SELECT*FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP))
	BEGIN
		IF(@TINHTRANG=N'Xác nhận')
		BEGIN
			IF((SELECT TONGSL FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)>0 AND(SELECT TONGTIEN FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)>0)
			UPDATE DONNHAPHANG SET TINHTRANG=@TINHTRANG WHERE MADONNHAP=@MADONNHAP
		END
		ELSE IF(@TINHTRANG=N'Đã huỷ')
		BEGIN
			UPDATE DONNHAPHANG SET TINHTRANG=@TINHTRANG WHERE MADONNHAP=@MADONNHAP
			DELETE FROM DSNHAPHANG WHERE MADONNHAP=@MADONNHAP
		END
	END
GO

/*---------------------------------- DSNHAPHANG ----------------------------------*/
--Insert
CREATE PROC sp_InDSNH @MADONNHAP INT,@MAMH INT,@SL INT
AS
	IF((EXISTS(SELECT*FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP))AND(EXISTS(SELECT*FROM MATHANG WHERE MAMH=@MAMH))
	AND(@SL<=(SELECT SLTON FROM MATHANG WHERE MAMH=@MAMH))
	AND((SELECT TINHTRANG FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)=N'Chờ xác nhận'))
	BEGIN
		DECLARE @MANCC INT = (SELECT MANCC FROM MATHANG WHERE MAMH=@MAMH)
		INSERT INTO DSNHAPHANG VALUES (@MADONNHAP,@MAMH,@SL,@MANCC)
		DECLARE @TONGSL INT=(SELECT TONGSL FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)+@SL
		DECLARE @TONGTIEN MONEY=(SELECT TONGTIEN FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)+(@SL*(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH))
		UPDATE DONNHAPHANG SET TONGSL=@TONGSL,TONGTIEN=@TONGTIEN WHERE MADONNHAP=@MADONNHAP
	END
GO

--Update
CREATE PROC sp_UpDSNH @MADONNHAP INT,@MAMH INT,@SL INT
AS
	IF((EXISTS(SELECT*FROM DSNHAPHANG WHERE MADONNHAP=@MADONNHAP AND MAMH=@MAMH))
	AND(@SL<=(SELECT SLTON FROM MATHANG WHERE MAMH=@MAMH))
	AND((SELECT TINHTRANG FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)=N'Chờ xác nhận'))
	BEGIN
		DECLARE @TONGSL_CU INT,@TONGSL_MOI INT,@TONGTIEN_CU MONEY,@TONGTIEN_MOI MONEY
		SET @TONGSL_CU=(SELECT TONGSL FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)
		SET @TONGSL_MOI=@TONGSL_CU-(SELECT SL FROM DSNHAPHANG WHERE MADONNHAP=@MADONNHAP AND MAMH=@MAMH)+@SL
		SET @TONGTIEN_CU=(SELECT TONGTIEN FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)
		SET @TONGTIEN_MOI=@TONGTIEN_CU-((SELECT SL FROM DSNHAPHANG WHERE MADONNHAP=@MADONNHAP AND MAMH=@MAMH)*(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH))+(@SL*(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH))
		UPDATE DSNHAPHANG SET SL=@SL WHERE MADONNHAP=@MADONNHAP AND MAMH=@MAMH
		UPDATE DONNHAPHANG SET TONGSL=@TONGSL_MOI,TONGTIEN=@TONGTIEN_MOI WHERE MADONNHAP=@MADONNHAP
	END
GO

--Delete
CREATE PROC sp_DelDSNH @MADONNHAP INT,@MAMH INT
AS
	IF((EXISTS(SELECT MADONNHAP FROM DSNHAPHANG WHERE MADONNHAP=@MADONNHAP AND MAMH=@MAMH))
	AND((SELECT TINHTRANG FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)=N'Chờ xác nhận'))
	BEGIN
		DECLARE @TONGSL_CU INT,@TONGSL_MOI INT,@TONGTIEN_CU MONEY,@TONGTIEN_MOI MONEY
		SET @TONGSL_CU=(SELECT TONGSL FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)
		SET @TONGSL_MOI=@TONGSL_CU-(SELECT SL FROM DSNHAPHANG WHERE MADONNHAP=@MADONNHAP AND MAMH=@MAMH)
		SET @TONGTIEN_CU=(SELECT TONGTIEN FROM DONNHAPHANG WHERE MADONNHAP=@MADONNHAP)
		SET @TONGTIEN_MOI=@TONGTIEN_CU-((SELECT SL FROM DSNHAPHANG WHERE MADONNHAP=@MADONNHAP AND MAMH=@MAMH)*(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH))
		DELETE FROM DSNHAPHANG WHERE MADONNHAP=@MADONNHAP AND MAMH=@MAMH
		UPDATE DONNHAPHANG SET TONGSL=@TONGSL_MOI,TONGTIEN=@TONGTIEN_MOI WHERE MADONNHAP=@MADONNHAP
	END
GO

/*----------------------------------DONTRAHANG----------------------------------*/
--Insert (Nếu được thì code cho nv chọn tên đối tác (tên ncc) thôi, không cần nhập trực tiếp
CREATE PROC sp_InDTH @NGUOILAP INT,@TENDOITAC NVARCHAR(50)
AS
	IF((EXISTS(SELECT*FROM NHANVIEN WHERE MANV=@NGUOILAP AND CHUCVU=N'Bán hàng'))AND EXISTS(SELECT*FROM NHACUNGCAP WHERE TENNCC=@TENDOITAC))
	BEGIN
		DECLARE @MADONTRA INT =(SELECT MAX(MADONTRA) FROM DONTRAHANG)+1
		IF(@MADONTRA IS NULL)
			SET @MADONTRA=1
		INSERT INTO DONTRAHANG VALUES (@MADONTRA,@NGUOILAP,GETDATE(),@TENDOITAC)
	END
GO

/*----------------------------------DSTRAHANG----------------------------------*/
--Insert
CREATE PROC sp_InDSTH @MADONTRA INT,@MAMH INT,@MAHD INT
AS
	IF((EXISTS(SELECT*FROM DONTRAHANG WHERE MADONTRA=@MADONTRA))AND(EXISTS(SELECT*FROM MATHANGLOI WHERE MAMH=@MAMH AND MAHD=@MAHD)))
	BEGIN
		DECLARE @SL INT,@LYDO NVARCHAR(50),@ID INT
		SET @ID=(SELECT MAX(ID) FROM DSTRAHANG)+1
		IF(@ID IS NULL)
			SET @ID=1
		SET @SL=(SELECT SL FROM MATHANGLOI WHERE MAMH=@MAMH AND MAHD=@MAHD)
		SET @LYDO=(SELECT LYDO FROM MATHANGLOI WHERE MAMH=@MAMH AND MAHD=@MAHD)
		INSERT INTO DSTRAHANG VALUES (@ID,@MADONTRA,@MAMH,@SL,@LYDO)
	END
GO

/*---------------------------------- HOADON ----------------------------------*/
--Update xác nhận thanh toán
CREATE PROC sp_UpHD @MAHD INT,@XACNHAN BIT
AS
	IF(@XACNHAN=1)
	BEGIN
		IF((SELECT TONGTIEN FROM HOADON WHERE MAHD=@MAHD)>0 AND
		(NOT EXISTS(SELECT*FROM HDTHE WHERE MAHD=@MAHD))OR(EXISTS(SELECT*FROM HDTHE WHERE MAHD=@MAHD AND XACNHAN=1)))
			UPDATE HOADON SET XACNHANTHANHTOAN=@XACNHAN WHERE MAHD=@MAHD
	END
GO

--Delete 
CREATE PROC sp_DelHD @MAHD INT
AS
	IF((SELECT XACNHANTHANHTOAN FROM HOADON WHERE MAHD=@MAHD)=0)
	BEGIN
		DELETE FROM HD_MH WHERE MAHD=@MAHD
		DELETE FROM HDTHE WHERE MAHD=@MAHD
		DELETE FROM HOADON WHERE MAHD=@MAHD
	END
GO

/*---------------------------------- MATHANGLOI ----------------------------------*/
--Insert 
CREATE PROC sp_InMHL @MAHD INT,@MAMH INT,@SL INT,@LYDO NVARCHAR(50)
AS
	IF((EXISTS(SELECT*FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH))AND(@SL<=(SELECT SL FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH)))
	BEGIN
	-- Trường hợp chỉ trả 1/10 mh trong hoá đơn thì sẽ set tình trạng mặt hàng trong HD_MH là 1, set số lượng bằng số lượng đã trả 
	-- và insert dòng mới tương ứng với số lượng hàng k trả, set lại tổng tiền của hoá đơn
		DECLARE @SL_MOI INT,@GIA MONEY,@TONGTIEN_MOI MONEY, @ID1 INT 
		SET @ID1=(SELECT ID FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH)
		SET @SL_MOI=(SELECT SL FROM HD_MH WHERE ID=@ID1)-@SL
		SET @GIA=(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH)
		SET @TONGTIEN_MOI=(@SL_MOI*@GIA)
		IF(@SL_MOI>0)
		BEGIN
			DECLARE @ID INT =(SELECT MAX(ID) FROM HD_MH)+1
			INSERT INTO HD_MH VALUES (@ID,@MAHD,@MAMH,@SL_MOI,@GIA,0)
		END
		UPDATE HD_MH SET TRAHANG=1,SL=@SL WHERE ID=@ID1
		UPDATE HOADON SET TONGTIEN=@TONGTIEN_MOI WHERE MAHD=@MAHD
		INSERT INTO MATHANGLOI VALUES(@MAHD,@MAMH,@SL,@LYDO)
	END
GO

--Update
-- Có thể update số lượng lớn hơn hoặc nhỏ hơn SL đã trả
CREATE PROC sp_UpMHL @MAHD INT,@MAMH INT,@SL INT,@LYDO NVARCHAR(50)
AS
	IF((EXISTS(SELECT*FROM MATHANGLOI WHERE MAHD=@MAHD AND MAMH=@MAMH))AND @SL>0 
	AND(@SL<=(SELECT SUM(SL) FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH)))
	BEGIN
		IF(@SL!=(SELECT SL FROM MATHANGLOI WHERE MAHD=@MAHD AND MAMH=@MAMH))
		BEGIN
			DECLARE @SL_HDMH INT,@TONGTIEN_MOI MONEY
			SET @SL_HDMH=(SELECT SUM(SL) FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH)-@SL --SL mới trong HD_MH
			SET @TONGTIEN_MOI=(@SL_HDMH*(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH))
			UPDATE HD_MH SET SL=@SL WHERE MAHD=@MAHD AND MAMH=@MAMH AND TRAHANG=1
			UPDATE HD_MH SET SL=@SL_HDMH WHERE MAHD=@MAHD AND MAMH=@MAMH AND TRAHANG=0
			UPDATE HOADON SET TONGTIEN=@TONGTIEN_MOI WHERE MAHD=@MAHD
		END
		UPDATE MATHANGLOI SET SL=@SL,LYDO=@LYDO WHERE MAHD=@MAHD AND MAMH=@MAMH
	END
GO

--Delete 
CREATE PROC sp_DelMHL @MAHD INT,@MAMH INT
AS
	IF(EXISTS(SELECT*FROM MATHANGLOI WHERE MAHD=@MAHD AND MAMH=@MAMH))
	BEGIN
		DECLARE @SL INT =(SELECT SUM(SL) FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH)
		IF((SELECT COUNT(*) FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH)>1)
			DELETE FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH AND TRAHANG=0
		UPDATE HD_MH SET SL=@SL,TRAHANG=0 WHERE MAHD=@MAHD AND MAMH=@MAMH
		DECLARE @TONGTIEN_MOI MONEY =(@SL*(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH))
		UPDATE HOADON SET TONGTIEN=@TONGTIEN_MOI WHERE MAHD=@MAHD
		DELETE FROM MATHANGLOI WHERE MAHD=@MAHD AND MAMH=@MAMH
	END
GO

--Trường hợp mặt hàng lỗi đạt ngưỡng và thông báo cho nhân viên (xử lí bên code)
CREATE PROC sp_TbMHL
AS
	IF((SELECT COUNT(*) FROM MATHANGLOI)>=30)
		PRINT N'Mặt hàng lỗi đã đạt đến ngưỡng. Đề nghị trả hàng!'
GO

/*---------------------------------- HDTHE ----------------------------------*/
-- Insert
CREATE PROC sp_InHDT @MAHD INT,@MATHE INT
AS
	IF(EXISTS(SELECT*FROM HOADON WHERE MAHD=@MAHD AND XACNHANTHANHTOAN=0 AND MATHE IS NOT NULL))
		INSERT INTO HDTHE VALUES(@MAHD,@MATHE,0)
GO

--Update
CREATE PROC sp_UpHDT @MAHD INT,@MATHE INT,@XACNHAN BIT --1 hđ có thể thanh toán bằng nhiều thẻ
AS
	IF(@XACNHAN=1 AND (EXISTS(SELECT*FROM HDTHE WHERE MAHD=@MAHD AND MATHE=@MATHE AND XACNHAN=0))) 
	--Do khi xác nhận thanh toán bên hoá đơn đã ràng buộc không được xác nhận thanh toán hđ khi thẻ chưa xác nhận nên không thêm điều kiện
		UPDATE HDTHE SET XACNHAN=@XACNHAN WHERE MAHD=@MAHD
GO

--Delete
CREATE PROC sp_DelHDT @MAHD INT,@MATHE INT
AS
	IF(EXISTS(SELECT*FROM HDTHE WHERE MAHD=@MAHD AND MATHE=@MATHE AND XACNHAN=0)) 
	--Nếu hđ thẻ đã xác nhận thì không được xoá
		DELETE FROM HDTHE WHERE MAHD=@MAHD AND MATHE=@MATHE
GO

/*---------------------------------- HD_MH ----------------------------------*/
--Insert
CREATE PROC sp_InHDMH @MAHD INT,@MAMH INT,@SL INT
AS
	IF((EXISTS(SELECT*FROM HOADON WHERE MAHD=@MAHD))AND(EXISTS(SELECT*FROM MATHANG WHERE MAMH=@MAMH))AND @SL>0)
	BEGIN
		DECLARE @GIA MONEY,@TONGTIEN MONEY,@ID INT
		SET @ID=(SELECT MAX(ID) FROM HD_MH)+1
		IF(@ID IS NULL)
			SET @ID=1
		SET @GIA=(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH)
		SET @TONGTIEN=(@SL*@GIA)+(SELECT TONGTIEN FROM HOADON WHERE MAHD=@MAHD)
		INSERT INTO HD_MH VALUES(@ID,@MAHD,@MAMH,@SL,@GIA,0)
		UPDATE HOADON SET TONGTIEN=@TONGTIEN WHERE MAHD=@MAHD
	END
GO

--Update
CREATE PROC sp_UpHDMH @MAHD INT,@MAMH INT,@SL INT
--Không update tình trạng trả hàng ở đây, chỉ up số lượng, muốn trả thì insert mặt hàng lỗi thì ở đây tự cập nhật tình trạng
AS
	IF((EXISTS(SELECT*FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH))AND @SL>0)
	BEGIN
		DECLARE @TONGTIEN_MOI MONEY,@TONGTIEN_CU MONEY,@ID INT
		SET @ID=(SELECT ID FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH AND TRAHANG=0)
		SET @TONGTIEN_CU=(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH)*(SELECT SL FROM HD_MH WHERE ID=@ID)
		SET @TONGTIEN_MOI=(SELECT TONGTIEN FROM HOADON WHERE MAHD=@MAHD)-@TONGTIEN_CU+(@SL*(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH))
		UPDATE HD_MH SET SL=@SL WHERE ID=@ID
		UPDATE HOADON SET TONGTIEN=@TONGTIEN_MOI WHERE MAHD=@MAHD
	END
GO

--Delete
CREATE PROC sp_DelHDMH @MAHD INT,@MAMH INT
AS
	IF((EXISTS(SELECT*FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH AND TRAHANG=0)))--Nếu hàng đã trả thì không được xoá
	BEGIN
		DECLARE @SL INT,@TONGTIEN MONEY,@ID INT
		SET @ID=(SELECT ID FROM HD_MH WHERE MAHD=@MAHD AND MAMH=@MAMH AND TRAHANG=0)
		SET @SL=(SELECT SL FROM HD_MH WHERE ID=@ID)
		SET @TONGTIEN=(SELECT TONGTIEN FROM HOADON WHERE MAHD=@MAHD)-(@SL*(SELECT GIA FROM MATHANG WHERE MAMH=@MAMH))
		DELETE FROM HD_MH WHERE ID=@ID
		UPDATE HOADON SET TONGTIEN=@TONGTIEN WHERE MAHD=@MAHD
	END
GO

/*---------------------------------- THONGKECMT ----------------------------------*/
--Update (Nhân viên khi thống kê phân loại sẽ thêm thông tin vào)
CREATE PROC sp_UpTKCmt @ID INT,@LOAICMT BIT,@NVTK INT
AS
	IF((EXISTS(SELECT*FROM THONGKECMT WHERE ID=@ID))AND(EXISTS(SELECT*FROM NHANVIEN WHERE MANV=@NVTK AND CHUCVU=N'Bán hàng')))
	BEGIN
		UPDATE THONGKECMT SET LOAICMT=@LOAICMT,NVTK=@NVTK WHERE ID=@ID
	END
GO

--Delete 
CREATE PROC sp_DelTKCmt @ID INT
AS
	IF(EXISTS(SELECT*FROM THONGKECMT WHERE ID=@ID))
	BEGIN
		DELETE FROM THONGKECMT WHERE ID=@ID
		DECLARE @EMAIL VARCHAR(50)=(SELECT EMAIL FROM THONGKECMT WHERE ID=@ID)
		IF((SELECT COUNT(*) FROM THONGKECMT WHERE EMAIL=@EMAIL AND LOAICMT=0)<=30)
			DELETE FROM DSDEN WHERE EMAIL=@EMAIL
	END
GO

/*---------------------------------- DSDEN ----------------------------------*/
--Delete
CREATE PROC sp_DelDSD @EMAIL VARCHAR(50)
AS
	IF(EXISTS(SELECT*FROM DSDEN WHERE EMAIL=@EMAIL))
	BEGIN
		IF((SELECT COUNT(*) FROM THONGKECMT WHERE EMAIL=@EMAIL AND LOAICMT=0)<=30)
			DELETE FROM DSDEN WHERE EMAIL=@EMAIL
	END
GO