CREATE DATABASE HTThuVien
USE HTThuVien
GO

CREATE TABLE SACH
(
	MASACH INT NOT NULL,
	TENSACH NVARCHAR(100),
	TENTACGIA NVARCHAR(50),
	GIA INT,
	SL INT,
	MANCC INT,
	LOAI NVARCHAR(50),
	TOMTAT NVARCHAR(1000),
	BIENMUC NVARCHAR(50),
	CHUDE NVARCHAR(50),
	PRIMARY KEY(MASACH)
)

CREATE TABLE NHANVIEN
(
	MANV INT NOT NULL,
	MATKHAU VARCHAR(50),
	HOTEN NVARCHAR(50),
	CHUCVU NVARCHAR(50)
	PRIMARY KEY(MANV)
)

CREATE TABLE NHACUNGCAP
(
	MANCC INT NOT NULL,
	TENNCC NVARCHAR(50)
	PRIMARY KEY(MANCC)
)

CREATE TABLE THANHLY
(
	ID INT NOT NULL,
	TINHTRANG NVARCHAR(50),
	PRIMARY KEY(ID)
)

CREATE TABLE DSTHANHLY
(
	ID INT NOT NULL,
	MASACH INT NOT NULL,
	LYDO NVARCHAR(100),
	THOIGIANTL DATE,
	KTRSAOLUU NVARCHAR(50),
	PRIMARY KEY(ID,MASACH)
)

CREATE TABLE DSDKTHE
(
	MAHV VARCHAR(50) NOT NULL,
	LOAIDK NVARCHAR(50),
	EMAIL VARCHAR(50),
	MALOP INT,
	LEPHI BIT,
	TINHTRANGHOC BIT
	PRIMARY KEY(MAHV)
)

CREATE TABLE THETHUVIEN
(
	MATHE VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SDT VARCHAR(50),
	TINHTRANG NVARCHAR(50)
	PRIMARY KEY(MATHE)
)

CREATE TABLE SINHVIEN
(
	MASV VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50),
	HE NVARCHAR(50),
	TRUONG NVARCHAR(50)
	PRIMARY KEY(MASV)
)

CREATE TABLE CANBO
(
	MACB VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50),
	LOAIDAOTAO NVARCHAR(50),
	TRUONG NVARCHAR(50)
	PRIMARY KEY(MACB)
)

CREATE TABLE LSGIAODICH
(
	ID INT NOT NULL,
	MATHE VARCHAR(50),
	MASACH INT,
	NGAYMUON DATE,
	HANTRA DATE,
	NGAYTRA DATE,
	TINHTRANG NVARCHAR(50)
	PRIMARY KEY(ID)
)

CREATE TABLE PHAT
(
	ID INT NOT NULL,
	ID_GIAODICH INT,
	TENSACH NVARCHAR(100),
	NGAYGHINHAN DATE,
	HOTEN NVARCHAR(50),
	TIENPHAT INT,
	NGUOIGHINHAN INT,
	LYDO NVARCHAR(50)
	PRIMARY KEY(ID)
)

ALTER TABLE THETHUVIEN ADD CONSTRAINT U_MATHE UNIQUE (MATHE)
GO

-- Tạo khoá ngoại
ALTER TABLE SACH ADD CONSTRAINT FK_SACH_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
GO

ALTER TABLE DSTHANHLY ADD CONSTRAINT FK_DSTHANHLY_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
GO
ALTER TABLE DSTHANHLY ADD CONSTRAINT FK_DSTHANHLY_THANHLY FOREIGN KEY (ID) REFERENCES THANHLY(ID)
GO

--ALTER TABLE DSDKTHE ADD CONSTRAINT FK_DSDK_SV FOREIGN KEY (MAHV) REFERENCES SINHVIEN(MASV)
--ALTER TABLE DSDKTHE ADD CONSTRAINT FK_DSDK_CB FOREIGN KEY (MAHV) REFERENCES CANBO(MACB)


--ALTER TABLE THETHUVIEN ADD CONSTRAINT FK_TTV_DSDK FOREIGN KEY (MATHE) REFERENCES DSDKTHE(MAHV)
ALTER TABLE LSGIAODICH ADD CONSTRAINT FK_LS_TTV FOREIGN KEY (MATHE) REFERENCES THETHUVIEN(MATHE)
GO
ALTER TABLE LSGIAODICH ADD CONSTRAINT FK_LS_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
GO

ALTER TABLE PHAT ADD CONSTRAINT FK_PHAT_LS FOREIGN KEY (ID_GIAODICH) REFERENCES LSGIAODICH(ID)
GO
ALTER TABLE PHAT ADD CONSTRAINT FK_PHAT_NV FOREIGN KEY (NGUOIGHINHAN) REFERENCES NHANVIEN(MANV)
GO
