USE HTThuVien
GO

--STORED PROC
/*---------------------------------------------SACH---------------------------------------------*/
--Insert
--Bộ phận bổ sung thêm sách mới
CREATE PROC sp_InSach(@TENSACH NVARCHAR(100),@TENTACGIA NVARCHAR(50),@GIA FLOAT,@SL INT,@MANCC INT)
AS
	IF(EXISTS(SELECT MANCC FROM NHACUNGCAP WHERE MANCC=@MANCC))
	BEGIN
		DECLARE @MASACH INT=(SELECT MAX(MASACH) FROM SACH)+1
		IF (@MASACH IS NULL)
			SET @MASACH=1
		INSERT INTO SACH VALUES (@MASACH,@TENSACH,@TENTACGIA,@GIA,@SL,@MANCC,NULL,NULL,NULL,NULL)
	END
GO

EXEC sp_InSach N'Her World',N'Thế giới thanh nữ',78000,40,1
GO

--Update
--Bộ phận phân loại phân loại sách
--Xem sách mới thêm
SELECT*FROM SACH WHERE LOAI IS NULL
--Phân loại sách
CREATE PROC sp_UpSachPhanLoai(@MASACH INT,@LOAI NVARCHAR(50),@TOMTAT NVARCHAR(1000))
AS
	UPDATE SACH SET LOAI=@LOAI,TOMTAT=@TOMTAT WHERE MASACH=@MASACH
GO

EXEC sp_UpSachPhanLoai 11,N'Tạp chí',N'Tạp chí Her World là một trong những tạp chí nổi tiếng ở Việt Nam'
GO

--Bộ phận biên mục
--Xem sách chưa được biên mục
SELECT*FROM SACH WHERE BIENMUC IS NULL
--Biên mục
CREATE PROC sp_UpSachBienMuc(@MASACH INT,@BIENMUC NVARCHAR(50))
AS
	UPDATE SACH SET BIENMUC=@BIENMUC WHERE MASACH=@MASACH
GO

EXEC sp_UpSachBienMuc 11,'0222#344'
GO

--Bộ phận chủ đề
--Xem sách chưa có chủ đề
SELECT*FROM SACH WHERE CHUDE IS NULL
--Thêm chủ đề
CREATE PROC sp_UpSachChuDe(@MASACH INT,@CHUDE NVARCHAR(50))
AS
	UPDATE SACH SET CHUDE=@CHUDE WHERE MASACH=@MASACH
GO

EXEC sp_UpSachChuDe 11,N'Thời trang'
GO

SELECT*FROM SACH
/*---------------------------------------------NHANVIEN---------------------------------------------*/
--Insert NV mới (MANV, mật khẩu được set mặc định giống nhau)
CREATE PROC sp_InNV(@HOTEN NVARCHAR(50),@CHUCVU NVARCHAR(50))
AS
	DECLARE @MANV INT =(SELECT MAX(MANV) FROM NHANVIEN)+1
	IF(@MANV IS NULL)
		SET @MANV=1
	INSERT INTO NHANVIEN VALUES (@MANV,@MANV,@HOTEN,@CHUCVU)
GO

EXEC sp_InNV N'Nguyễn Hoàng Thảo Vân',N'Thủ thư'
GO

--Update mật khẩu
CREATE PROC sp_UpPass(@MANV INT,@MATKHAU VARCHAR(50),@MATKHAUMOI VARCHAR(50))
AS
	IF(EXISTS(SELECT MANV FROM NHANVIEN WHERE @MANV=MANV AND @MATKHAU=MATKHAU))
		UPDATE NHANVIEN SET MATKHAU=@MATKHAUMOI WHERE MANV=@MANV
GO

EXEC sp_UpPass 18,'18','NV18'
GO

SELECT*FROM NHANVIEN
/*---------------------------------------------NHACUNGCAP---------------------------------------------*/
--Insert
CREATE PROC sp_InNCC(@TENNCC NVARCHAR(50))
AS
	DECLARE @MANCC INT=(SELECT MAX(MANCC) FROM NHACUNGCAP)+1
	IF (@MANCC IS NULL)
		SET @MANCC=1
	INSERT INTO NHACUNGCAP VALUES (@MANCC,@TENNCC)
GO

EXEC sp_InNCC N'R4 BCD'
GO
SELECT*FROM NHACUNGCAP
/*---------------------------------------------THANHLY---------------------------------------------*/
--Insert
CREATE PROC sp_InThanhLy
AS
	DECLARE @ID INT=(SELECT MAX(ID) FROM THANHLY)+1
	IF(@ID IS NULL)
		SET @ID=1
	INSERT INTO THANHLY VALUES (@ID,N'Chờ xác nhận')
GO
EXEC sp_InThanhLy
GO

/*---------------------------------------------DSTHANHLY---------------------------------------------*/
--Insert
CREATE PROC sp_InDSTL(@ID INT,@MASACH INT,@LYDO NVARCHAR(100),@KTRSAOLUU NVARCHAR(50))
AS
	IF((EXISTS(SELECT MASACH FROM SACH WHERE MASACH=@MASACH)) AND EXISTS(SELECT ID FROM THANHLY WHERE ID=@ID) 
	AND NOT EXISTS(SELECT MASACH FROM DSTHANHLY WHERE MASACH=@MASACH)) 
	BEGIN
		DECLARE @THOIGIANTL DATE = (SELECT DATEADD(DAY,30,GETDATE()))
		INSERT INTO DSTHANHLY VALUES (@ID,@MASACH,@LYDO,@THOIGIANTL,@KTRSAOLUU,N'Chờ xác nhận')
	END
GO

EXEC sp_InDSTL 11,N'Không hợp thị hiếu',N'Có 2 bản sao lưu'
GO
SELECT*FROM DSTHANHLY
--Xoá các sách trong bảng thanh lý và bẳng sách sau khi đã xác nhận thanh lý (Xoá tay)

/*---------------------------------------------DSDKTHE---------------------------------------------*/
--Insert
CREATE PROC sp_InDS(@MAHV VARCHAR(50),@LOAIDK NVARCHAR(50),@EMAIL VARCHAR(50),@LEPHI BIT)
AS
	IF(@LOAIDK IN ('Nhóm','Cá nhân'))
	BEGIN
		IF((EXISTS(SELECT MASV FROM SINHVIEN WHERE MASV=@MAHV)) OR ((EXISTS(SELECT MACB FROM CANBO WHERE MACB=@MAHV)) AND @LOAIDK='Cá nhân'))
		/*Do ở trên đã xét trong nhóm và cá nhân mà cán bộ chỉ đc đăng kí cá nhân nên thêm dị*/
		BEGIN
			INSERT INTO DSDKTHE VALUES(@MAHV,@LOAIDK,@EMAIL,NULL,@LEPHI,0)
			DECLARE @SL INT =(SELECT COUNT(*) FROM DSDKTHE WHERE TINHTRANGHOC=0)
			IF(@SL>=30)
			BEGIN
				DECLARE @MALOP INT=(SELECT MAX(MALOP) FROM DSDKTHE)+1
				IF(@MALOP IS NULL)
					SET @MALOP=1
				UPDATE DSDKTHE SET MALOP=@MALOP WHERE TINHTRANGHOC=0 
				/*Do số lượng học viên chưa học (TINHTRANGHOC=0) là 30 nên up như vậy luôn k cần thêm đk khác*/
			END
		END
	END
GO

EXEC sp_InDS 'SV100',N'Cá nhân','sv100@gmail.com',0
GO

--Update
CREATE PROC sp_UpDS(@MAHV VARCHAR(50),@LEPHI BIT,@TINHTRANGHOC BIT)
AS
	IF(EXISTS(SELECT MAHV FROM DSDKTHE WHERE MAHV=@MAHV))
	BEGIN
		IF(@TINHTRANGHOC=1)
		BEGIN
			IF((SELECT MALOP FROM DSDKTHE WHERE MAHV=@MAHV) IS NOT NULL)
			BEGIN
				UPDATE DSDKTHE SET LEPHI=@LEPHI,TINHTRANGHOC=@TINHTRANGHOC WHERE MAHV=@MAHV
				IF(@LEPHI=1 AND @TINHTRANGHOC=1)
				BEGIN
					IF(NOT EXISTS(SELECT MATHE FROM THETHUVIEN WHERE MATHE=@MAHV)) /*Kiểm tra học viên đã từng đăng kí thẻ hay chưa*/
					BEGIN 
						DECLARE @HOTEN NVARCHAR(100)
						IF(EXISTS(SELECT MASV FROM SINHVIEN WHERE MASV=@MAHV))
							SET @HOTEN=(SELECT HOTEN FROM SINHVIEN WHERE MASV=@MAHV)
						ELSE IF (EXISTS(SELECT MACB FROM CANBO WHERE MACB=@MAHV))
							SET @HOTEN=(SELECT HOTEN FROM CANBO WHERE MACB=@MAHV)
	
						INSERT INTO THETHUVIEN VALUES (@MAHV,@HOTEN,NULL,NULL,'Hợp lệ')
						DELETE FROM DSDKTHE WHERE MAHV=@MAHV
					END
				END
			END
		END
	END
GO

/*---------------------------------------------THETHUVIEN---------------------------------------------*/
--Update (Insert ở trong phần update của DSDKTHE)
CREATE PROC sp_UpTTV(@MATHE VARCHAR(50),@DIACHI NVARCHAR(100),@SDT VARCHAR(50))
AS
	IF(EXISTS(SELECT MATHE FROM THETHUVIEN WHERE MATHE=@MATHE))
		UPDATE THETHUVIEN SET DIACHI=@DIACHI, SDT=@SDT WHERE MATHE=@MATHE
GO
	

/*---------------------------------------------SINHVIEN---------------------------------------------*/
--Bảng dữ liệu của trường, chỉ thêm dữ liệu k được sử dụng tới
/*---------------------------------------------CANBO---------------------------------------------*/
--Bảng dữ liệu của trường, chỉ thêm dữ liệu k được sử dụng tới


/*---------------------------------------------LSGIAODICH---------------------------------------------*/
--Hiển thị độc giả không hợp lệ, thông tin mượn sách của độc giả
--DROP PROC sp_ViewTinhTrang
CREATE PROC sp_ViewTinhTrang(@MATHE VARCHAR(50))
AS
	IF(EXISTS(SELECT MATHE FROM THETHUVIEN WHERE MATHE=@MATHE))
	BEGIN
		SELECT S.TENSACH,LS.NGAYMUON,LS.HANTRA,CAST(DATEDIFF(DAY,GETDATE(),HANTRA) AS INT) AS SONGAYCONLAI INTO TEMP FROM LSGIAODICH LS, SACH S WHERE LS.MATHE=@MATHE AND LS.MASACH=S.MASACH ORDER BY NGAYMUON
		--Update tình trạng thẻ k hợp lệ khi độc giả chưa trả sách (mỗi lần mượn chỉ được 2 cuốn trong 2 tuần)
		IF((SELECT COUNT(*) FROM LSGIAODICH WHERE MATHE=@MATHE AND NGAYTRA IS NULL)>=2)
		BEGIN
			UPDATE THETHUVIEN SET TINHTRANG=N'Không hợp lệ'
			PRINT 'Cảnh báo! Thẻ không hợp lệ!'
		END
		ELSE 
		BEGIN 
			DECLARE @TT NVARCHAR(50),@I INT, @MAX INT
			SET @MAX=(SELECT MAX(ID) FROM LSGIAODICH)
			SET @I=1
			ALTER TABLE TEMP ADD TINHTRANG NVARCHAR(50)
			WHILE (@I<=@MAX)
			BEGIN
				SET @TT=(SELECT TINHTRANG FROM LSGIAODICH WHERE ID=@I AND MATHE=@MATHE)
				IF(@TT=N'Chưa trả')			
				BEGIN
					UPDATE TEMP SET TINHTRANG=N'Quá hạn' WHERE SONGAYCONLAI<0
					UPDATE TEMP SET TINHTRANG=N'Sắp đến hạn' WHERE SONGAYCONLAI<=2 AND SONGAYCONLAI>=0
					UPDATE TEMP SET TINHTRANG=N'Bình thường' WHERE SONGAYCONLAI>2
				END
				ELSE IF(@TT!=N'Chưa trả')
					UPDATE TEMP SET SONGAYCONLAI=0,TINHTRANG=@TT WHERE TENSACH IS NOT NULL
				--Nếu sách đã trả thì set số ngày còn lại trong bảng TEMP=0
				SET @I=@I+1
			END
			SELECT*FROM TEMP
		END
		DROP TABLE TEMP
	END
GO

EXEC sp_ViewTinhTrang 'SV7'
GO
SELECT*FROM LSGIAODICH

--Hiển thị sách khi quét gáy sách
CREATE PROC sp_ViewSach(@MASACH INT)
AS
	IF(EXISTS(SELECT MASACH FROM SACH WHERE MASACH=@MASACH))
	BEGIN
		SELECT MASACH,TENSACH,TENTACGIA FROM SACH WHERE MASACH=@MASACH
		IF((SELECT LOAI FROM SACH WHERE MASACH=@MASACH) IN (N'Tham khảo',N'Báo',N'Tạp chí'))
			PRINT N'Sách không được phép mượn!'
	END
GO

EXEC sp_ViewSach 5
GO

--Insert
CREATE PROC sp_InLS(@MATHE VARCHAR(50),@MASACH INT)
AS
	IF((EXISTS(SELECT MATHE FROM THETHUVIEN WHERE MATHE=@MATHE AND TINHTRANG=N'Hợp lệ'))AND(EXISTS(SELECT MASACH FROM SACH WHERE MASACH=@MASACH)))
	BEGIN
		DECLARE @ID INT=(SELECT MAX(ID) FROM LSGIAODICH)+1
		IF(@ID IS NULL)
			SET @ID=1
		DECLARE @HANTRA DATE=(SELECT DATEADD(DAY,14,GETDATE()))
		INSERT INTO LSGIAODICH VALUES(@ID,@MATHE,@MASACH,GETDATE(),@HANTRA,NULL,N'Chưa trả')
	END
GO

EXEC sp_InLS 'SV1',10
GO
SELECT*FROM LSGIAODICH
--Update khi độc giả trả sách
CREATE PROC sp_UpLS_NgayTra(@ID INT,@MATSACH BIT)
AS
	IF(EXISTS(SELECT ID FROM LSGIAODICH WHERE ID=@ID))
	BEGIN
		DECLARE @NGAYTRA DATE =(SELECT GETDATE())
		DECLARE @NGAY INT =(SELECT CAST(DATEDIFF(DAY,@NGAYTRA,HANTRA)AS INT) FROM LSGIAODICH WHERE ID=@ID)
		DECLARE @TINHTRANG NVARCHAR(50)
		IF(@MATSACH=1)
			SET @TINHTRANG = N'Mất sách'
		ELSE IF(@MATSACH=0)
		BEGIN
			IF(@NGAY<0)
				SET @TINHTRANG = N'Quá hạn'
			ELSE
				SET @TINHTRANG = N'Đã trả'
		END
		UPDATE LSGIAODICH SET NGAYTRA=@NGAYTRA,TINHTRANG=@TINHTRANG WHERE ID=@ID
	END
GO

EXEC sp_UpLS_NgayTra 7,0
GO

/*---------------------------------------------PHAT---------------------------------------------*/
--Insert
CREATE PROC sp_InPhat (@ID_GD INT,@TENSACH NVARCHAR(100),@HOTEN NVARCHAR(50),@NGUOIGHINHAN INT,@LYDO NVARCHAR(100))
AS
	IF((EXISTS(SELECT TENSACH FROM SACH S, LSGIAODICH LS WHERE S.MASACH=LS.MASACH AND LS.ID=@ID_GD AND S.TENSACH=@TENSACH)) AND 
		(EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@NGUOIGHINHAN)) AND (NOT EXISTS(SELECT*FROM PHAT WHERE ID_GIAODICH=@ID_GD)) AND
		(@LYDO IN (N'Hư hỏng', N'Mất sách', N'Quá hạn')))
	BEGIN
		DECLARE @ID int, @TIENPHAT INT, @NGAYGHINHAN DATE
		SET @ID=(SELECT MAX(ID) FROM PHAT)+1
		IF(@ID IS NULL)
			SET @ID=1;
		SET @NGAYGHINHAN = (SELECT GETDATE())
		IF(@LYDO=N'Quá hạn')
		BEGIN
			DECLARE @NGAYMUON DATE = (SELECT NGAYMUON FROM LSGIAODICH WHERE ID=@ID_GD)
			DECLARE @NGAY INT = CAST (DATEDIFF(DAY,@NGAYMUON,@NGAYGHINHAN) AS INT)
			IF(@NGAY<=30)
				SET @TIENPHAT=@NGAY*1000
			ELSE IF(@NGAY>30)
				SET @TIENPHAT=30000 + (@NGAY-30)*2000
		END
		ELSE
			SET @TIENPHAT=50000+ (SELECT GIA FROM SACH WHERE @TENSACH=TENSACH)
		INSERT INTO PHAT VALUES (@ID,@ID_GD,@TENSACH,@NGAYGHINHAN,@HOTEN,@TIENPHAT,@NGUOIGHINHAN,@LYDO)
	END
GO
SELECT*FROM PHAT