CREATE DATABASE NGHIEPVU
USE NGHIEPVU
GO

CREATE TABLE NHACUNGCAP
(
	MA_NCC INT PRIMARY KEY,
	TEN_NCC NVARCHAR(100),
	DIACHI NVARCHAR(100),
	MADKKD VARCHAR(100),
	MATKHAU NVARCHAR(100),
	WEBSITE NVARCHAR(100),
	EMAIL NVARCHAR(100),
	HOTLINE VARCHAR(100),
	QUYMO NVARCHAR(10),
	NGAYTL DATE,
	LOAI NVARCHAR(10),
	DAIDIEN NVARCHAR(100),
	CHUCVU NVARCHAR(100),
	EMAILPER NVARCHAR(100),
	SDT VARCHAR(100),
	TRANGTHAIXN BIT
)
 
CREATE TABLE MATHANG
(
	MAMH INT PRIMARY KEY,
	TENMH NVARCHAR(100),
	LOAIHANG NVARCHAR(100),
	THUONGHIEU NVARCHAR(100),
	GIATIEN FLOAT,
	TGBAOHANH INT
)

CREATE TABLE MH_NCC
(
	MAMH INT NOT NULL,
	MA_NCC INT NOT NULL,
	SOLUONG INT
)

CREATE TABLE THONGKEMH
(
	MA_NCC INT NOT NULL,
	MAMH INT NOT NULL,
	NAMTK INT NOT NULL,
	SL_BAN INT,
	SL_TON INT,
	DOANHTHU FLOAT
)

CREATE TABLE NHANVIEN
(
	MANV INT PRIMARY KEY,
	HOTEN NVARCHAR(100),
	CHUCVU NVARCHAR(100),
	MATKHAU NVARCHAR(100)
)

CREATE TABLE KHO
(
	MAKHO INT PRIMARY KEY,
	DIACHI NVARCHAR(100),
	SLCHUA INT
)

CREATE TABLE KHO_NV
(
	MAKHO INT NOT NULL,
	MANV INT NOT NULL
)

CREATE TABLE THANHTICHNV
(
	MANV INT NOT NULL,
	NAM INT NOT NULL,
	SODON_HOANTHANH INT,
	SO_REPORT INT,
	DANHGIA NVARCHAR(100)
)

CREATE TABLE TKKHACHHANG
(
	MATK INT PRIMARY KEY,
	HOTEN NVARCHAR(100),
	GIOITINH NVARCHAR(10),
	NGAYSINH DATE,
	EMAIL NVARCHAR(100),
	TENTK NVARCHAR(100),
	MATKHAU NVARCHAR(100)
)

CREATE TABLE DIACHIKH
(
	MATK INT PRIMARY KEY ,
	DIACHI NVARCHAR(100),
	PHUONG NVARCHAR(100),
	QUAN_HUYEN NVARCHAR(100),
	TINH_TP NVARCHAR(100)
)

CREATE TABLE HOADON
(
	MAHD INT PRIMARY KEY,
	MATK INT,
	NGAYDAT DATE,
	MAGG VARCHAR(100),
	TINHTRANG NVARCHAR(100),
	HUYDON BIT,
	PTTT NVARCHAR(100),
	STK VARCHAR(100),
	TONGTIEN FLOAT,
	DANHGIA BIT
)

CREATE TABLE LSDONHANG
(
	MAHD INT NOT NULL,
	NGAYMUA DATE NOT NULL,
	TONGTIEN FLOAT,
	TRANGTHAI NVARCHAR(100)
)

CREATE TABLE PHIEUBAOHANH
(
	STT INT PRIMARY KEY,
	MAHD INT,
	MAMH INT,
	NGAYBH DATE,
	TINHTRANGMH NVARCHAR(100),
	TINHTRANGBH NVARCHAR(100),
	CHIPHI FLOAT
)

CREATE TABLE MH_HD
(
	MAHD INT NOT NULL,
	MAMH INT NOT NULL,
	MA_NCC INT NOT NULL,
	SL INT,
	GIATIEN FLOAT,
	THANHTIEN FLOAT
)

CREATE TABLE PHIEUTRAHANG
(
	MA_PTRA INT PRIMARY KEY,
	MAHD INT,
	NGAYTRA DATE
)

CREATE TABLE PHIEUDOIHANG
(
	MA_PDOI INT PRIMARY KEY,
	MAHD INT,
	NGAYDOI DATE
)

CREATE TABLE PHIEUGIAOHANG
(
	MA_PGIAO INT PRIMARY KEY,
	MAHD INT,
	MANV INT,
	KHUVUC NVARCHAR(100),
	DIACHI NVARCHAR(100),
	NGAYXUAT DATE,
	NGAYGIAO DATE,
	CHIPHI FLOAT
)

CREATE TABLE PHIEUGUIHANG
(
	MA_PGUI INT PRIMARY KEY,
	MA_NCC INT,
	MAKHO INT,
	NGAYGUIDK DATE,
	NGAYNHAP DATE,
	TINHTRANG NVARCHAR(100),
	SLTON INT
)

CREATE TABLE PGH_MH
(
	MA_PGUI INT NOT NULL,
	MAMH INT NOT NULL,
	SOLUONG INT,
	NGAYXUAT DATE
)

CREATE TABLE DANHGIANCC
(
	NAM INT NOT NULL,
	MA_NCC INT NOT NULL,
	SODG_TOT INT,
	SODG_XAU INT,
	DANHGIA NVARCHAR(100)
)

CREATE TABLE TK_MH
(
	MATK INT NOT NULL,
	MAMH INT NOT NULL,
	MA_NCC INT NOT NULL,
	SL INT
)

GO

--PK
ALTER TABLE MH_NCC ADD CONSTRAINT PK_MHNCC PRIMARY KEY (MA_NCC,MAMH)
ALTER TABLE THONGKEMH ADD CONSTRAINT PK_TKMH PRIMARY KEY (MA_NCC,MAMH,NAMTK)
ALTER TABLE KHO_NV ADD CONSTRAINT PK_KNV PRIMARY KEY (MAKHO,MANV)
ALTER TABLE THANHTICHNV ADD CONSTRAINT PK_TTNV PRIMARY KEY (MANV,NAM)
ALTER TABLE LSDONHANG ADD CONSTRAINT PK_LSDH PRIMARY KEY (MAHD,NGAYMUA)
ALTER TABLE MH_HD ADD CONSTRAINT PK_MHHD PRIMARY KEY (MAHD,MAMH,MA_NCC)
ALTER TABLE PGH_MH ADD CONSTRAINT PK_PGMH PRIMARY KEY (MA_PGUI,MAMH)
ALTER TABLE DANHGIANCC ADD CONSTRAINT PK_DGNCC PRIMARY KEY (NAM,MA_NCC)
ALTER TABLE TK_MH ADD CONSTRAINT PK_TKHMH PRIMARY KEY (MATK,MAMH,MA_NCC)
GO

ALTER TABLE NHACUNGCAP ADD CONSTRAINT U_MADKKD UNIQUE (MADKKD)
ALTER TABLE NHACUNGCAP ADD CONSTRAINT C_QUYMO CHECK (QUYMO IN (N'Nhỏ',N'Vừa',N'Lớn'))
ALTER TABLE NHACUNGCAP ADD CONSTRAINT C_LOAI CHECK (LOAI IN ('A','B','C','D'))

ALTER TABLE DANHGIANCC ADD CONSTRAINT C_DANHGIA CHECK ( DANHGIA IN (N'Đạt',N'Không đạt'))

ALTER TABLE TKKHACHHANG ADD CONSTRAINT U_TENTK UNIQUE (TENTK)
ALTER TABLE TKKHACHHANG ADD CONSTRAINT C_GIOITINH CHECK (GIOITINH IN (N'Nam',N'Nữ'))

ALTER TABLE THANHTICHNV ADD CONSTRAINT C_DANHGIANV CHECK (DANHGIA IN (N'Kém',N'Trung bình', N'Khá', N'Tốt',N'Xuất sắc'))

ALTER TABLE PHIEUGIAOHANG ADD CONSTRAINT C_KHUVUC CHECK (KHUVUC IN (N'Nội thành', N'Ngoại thành'))
GO

--FK
ALTER TABLE MH_NCC ADD CONSTRAINT FK_MHNCC_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
ALTER TABLE MH_NCC ADD CONSTRAINT FK_MHNCC_NCC FOREIGN KEY (MA_NCC) REFERENCES NHACUNGCAP(MA_NCC)

ALTER TABLE THONGKEMH ADD CONSTRAINT FK_TKMH_NCC FOREIGN KEY (MA_NCC) REFERENCES NHACUNGCAP(MA_NCC)
ALTER TABLE THONGKEMH ADD CONSTRAINT FK_TKMH_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)

ALTER TABLE KHO_NV ADD CONSTRAINT FK_KNV_K FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO)
ALTER TABLE KHO_NV ADD CONSTRAINT FK_KNV_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE THANHTICHNV ADD CONSTRAINT FK_TTNV_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MATK) REFERENCES TKKHACHHANG(MATK)

ALTER TABLE LSDONHANG ADD CONSTRAINT FK_LSDH_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE PHIEUBAOHANH ADD CONSTRAINT FK_PBH_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE PHIEUBAOHANH ADD CONSTRAINT FK_PBH_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)

ALTER TABLE MH_HD ADD CONSTRAINT FK_MHHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE MH_HD ADD CONSTRAINT FK_MHHD_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
ALTER TABLE MH_HD ADD CONSTRAINT FK_MHHD_NCC FOREIGN KEY (MA_NCC) REFERENCES NHACUNGCAP(MA_NCC)

ALTER TABLE PHIEUTRAHANG ADD CONSTRAINT FK_PTH_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE PHIEUDOIHANG ADD CONSTRAINT FK_PDH_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE PHIEUGIAOHANG ADD CONSTRAINT FK_PGIH_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE PHIEUGIAOHANG ADD CONSTRAINT FK_PGIH_MH FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE PHIEUGUIHANG ADD CONSTRAINT FK_PGH_NCC FOREIGN KEY (MA_NCC) REFERENCES NHACUNGCAP(MA_NCC)
ALTER TABLE PHIEUGUIHANG ADD CONSTRAINT FK_PGH_K FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO)

ALTER TABLE PGH_MH ADD CONSTRAINT FK_PGMH_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
ALTER TABLE PGH_MH ADD CONSTRAINT FK_PGMH_PG FOREIGN KEY (MA_PGUI) REFERENCES PHIEUGUIHANG(MA_PGUI)

ALTER TABLE DANHGIANCC ADD CONSTRAINT FK_DGNCC_NCC FOREIGN KEY (MA_NCC) REFERENCES NHACUNGCAP(MA_NCC)

ALTER TABLE TK_MH ADD CONSTRAINT FK_TKHMH_NCC FOREIGN KEY (MA_NCC) REFERENCES NHACUNGCAP(MA_NCC)
ALTER TABLE TK_MH ADD CONSTRAINT FK_TKHMH_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
ALTER TABLE TK_MH ADD CONSTRAINT FK_TKHMH_TK FOREIGN KEY (MATK) REFERENCES TKKHACHHANG(MATK)

ALTER TABLE DIACHIKH ADD CONSTRAINT FK_DCKH_TKKH FOREIGN KEY (MATK) REFERENCES TKKHACHHANG(MATK)
GO