USE NGHIEPVU
GO
----------------------------------------------------------------NHÀ CUNG CẤP----------------------------------------------------------------
/* NHÀ CUNG CẤP */
--INSERT
CREATE PROC sp_InNCC 
	@TEN_NCC NVARCHAR(100),
	@DIACHI NVARCHAR(100),
	@MADKKD VARCHAR(100),
	@MATKHAU NVARCHAR(100),
	@WEBSITE NVARCHAR(100),
	@EMAIL NVARCHAR(100),
	@HOTLINE VARCHAR(100),
	@QUYMO NVARCHAR(10),
	@NGAYTL DATE,
	@LOAI NTEXT,
	@DAIDIEN NVARCHAR(100),
	@CHUCVU NVARCHAR(100),
	@EMAILPER TEXT,
	@SDT VARCHAR(100),
	@TRANGTHAIXN BIT
AS
BEGIN
DECLARE @MA_NCC INT
SET @MA_NCC =  (SELECT MAX(MA_NCC) FROM NHACUNGCAP)
	BEGIN TRAN
	BEGIN TRY
		IF (@MA_NCC IS NULL)
			BEGIN	
				SET @MA_NCC = 1
				INSERT INTO NHACUNGCAP VALUES(@MA_NCC,@TEN_NCC,@DIACHI,@MADKKD,@MATKHAU,@WEBSITE,@EMAIL,@HOTLINE,@QUYMO,@NGAYTL,@LOAI,@DAIDIEN,@CHUCVU,@EMAILPER,@SDT,@TRANGTHAIXN)
			END
		ELSE
			BEGIN
				SET @MA_NCC = @MA_NCC + 1
				INSERT INTO NHACUNGCAP VALUES(@MA_NCC,@TEN_NCC,@DIACHI,@MADKKD,@MATKHAU,@WEBSITE,@EMAIL,@HOTLINE,@QUYMO,@NGAYTL,@LOAI,@DAIDIEN,@CHUCVU,@EMAILPER,@SDT,@TRANGTHAIXN)
			END
		COMMIT TRAN
		PRINT N'Thêm nhà cung cấp thành công!'
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT N'Thêm nhà cung cấp thất bại!Xin thử lại!'
	END CATCH
END
GO

--LOGIN
CREATE PROC sp_LoginNCC
	@MADKKD VARCHAR(100),
	@MATKHAU NVARCHAR(100)
AS
BEGIN TRAN
BEGIN TRY
	IF (EXISTS (SELECT MADKKD FROM NHACUNGCAP WHERE MADKKD= @MADKKD))
		BEGIN
			IF(EXISTS (SELECT MATKHAU FROM NHACUNGCAP WHERE MATKHAU=@MATKHAU))
			SELECT*FROM NHACUNGCAP WHERE MADKKD=@MADKKD
		END
	COMMIT TRAN
	PRINT N'Nhà cung cấp đăng nhập thành công!'
END TRY
BEGIN CATCH
	ROLLBACK TRAN
	PRINT N'Lỗi!Đăng nhập thất bại!'
END CATCH
GO

-- UPDATE
CREATE PROC sp_UPNCC
	@TEN_NCC NVARCHAR(50),
	@DIACHI NVARCHAR(50),
	@MADKKD VARCHAR(10),
	@MATKHAU VARCHAR(100),
	@WEBSITE NVARCHAR(50),
	@EMAIL NVARCHAR(50),
	@HOTLINE VARCHAR(10),
	@QUYMO NVARCHAR(50),
	@NGAYTL DATE,
	@LOAI NVARCHAR(50),
	@DAIDIEN NVARCHAR(50),
	@CHUCVU NVARCHAR(50),
	@EMAILPER NVARCHAR(50),
	@SDT VARCHAR(10)
AS
BEGIN
BEGIN TRAN
	BEGIN TRY
		IF (EXISTS (SELECT MADKKD FROM NHACUNGCAP WHERE @MADKKD = MADKKD))
			UPDATE NHACUNGCAP SET TEN_NCC=@TEN_NCC,DIACHI=@DIACHI,MATKHAU=@MATKHAU,WEBSITE=@WEBSITE,EMAIL=@EMAIL,HOTLINE=@HOTLINE,QUYMO=@QUYMO,NGAYTL=@NGAYTL,LOAI=@LOAI,DAIDIEN=@DAIDIEN,CHUCVU=@CHUCVU,EMAILPER=@EMAILPER,SDT=@SDT
			WHERE MADKKD = @MADKKD
		COMMIT TRAN
		PRINT N'Cập nhật nhà cung cấp thành công!'
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT N'Lỗi!Cập nhật nhà cung cấp thất bại!'
	END CATCH
END
GO

--DELETE
CREATE PROC sp_DelNCC @MANV INT, @MATKHAU VARCHAR(100), @MADKKD VARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
		IF (EXISTS (SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND CHUCVU= N'Quản lý hệ thống'))
		BEGIN
			IF (EXISTS (SELECT MATKHAU FROM NHANVIEN WHERE MATKHAU=@MATKHAU))
			BEGIN
				IF (@MADKKD IN (SELECT MADKKD FROM NHACUNGCAP))
				BEGIN
					DECLARE @MA_NCC INT = (SELECT MA_NCC FROM NHACUNGCAP WHERE MADKKD = @MADKKD)
					DELETE FROM MH_NCC WHERE MA_NCC=@MA_NCC
					DELETE FROM NHACUNGCAP WHERE  MADKKD=@MADKKD
					COMMIT TRAN
					PRINT N'Xóa nhà cung cấp thành công!'
				END
			END
		END
		ELSE 
		BEGIN
			ROLLBACK TRAN
			PRINT N'Lỗi!Xóa nhà cung cấp thất bại!'
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT N'Lỗi!Xóa nhà cung cấp thất bại!'
	END CATCH
GO

/* ĐÁNH GIÁ NCC */
--INSERT
CREATE PROC sp_InDGNCC @NAM INT,@MA_NCC INT,@SODG_TOT INT,@SODG_XAU INT --Số đánh giá tốt và xấu sẽ được thực hiện bằng truy vấn
AS
	IF(NOT EXISTS(SELECT MA_NCC FROM NHACUNGCAP WHERE MA_NCC=@MA_NCC))
		PRINT N'Lỗi!Nhà cung cấp không tồn tại!'
	ELSE
	BEGIN
		IF(@SODG_TOT<=@SODG_XAU)
		BEGIN
			INSERT INTO DANHGIANCC VALUES(@NAM,@MA_NCC,@SODG_TOT,@SODG_XAU,N'Không đạt')
		END
		ELSE
		BEGIN
			INSERT INTO DANHGIANCC VALUES(@NAM,@MA_NCC,@SODG_TOT,@SODG_XAU,N'Đạt')
		END
		SELECT*FROM DANHGIANCC WHERE NAM=@NAM AND MA_NCC=@MA_NCC
		PRINT N'Đánh giá nhà cung cấp thành công!'
	END
GO

--KHÔNG CHO PHÉP DELETE VÀ UPDATE

*/
/* PHIẾU GỬI HÀNG */
--INSERT
CREATE PROC sp_InPGH
	@MA_NCC INT,
	@MAKHO INT,
	@NGAYGUIDK DATE
AS
	DECLARE @MA_PGUI INT=(SELECT MAX (MA_PGUI) FROM dbo.PHIEUGUIHANG)
	DECLARE @TINHTRANG NVARCHAR(100)=N'Không thể lập đơn'
	IF ((NOT EXISTS (SELECT MA_NCC FROM MH_NCC WHERE MA_NCC= @MA_NCC)) OR (NOT EXISTS (SELECT MAKHO FROM KHO WHERE MAKHO = @MAKHO)))
		PRINT N'Lỗi!Thông tin đã nhập không chính xác!'
	ELSE
	BEGIN
		IF (@MA_PGUI IS NULL)
		BEGIN
			SET @MA_PGUI = 1
			SET @TINHTRANG  = N'Đã xác nhận'
			INSERT INTO PHIEUGUIHANG VALUES (@MA_PGUI,@MA_NCC,@MAKHO,@NGAYGUIDK,NULL,@TINHTRANG,NULL)
		END
		ELSE
		BEGIN
			SET @MA_PGUI = @MA_PGUI + 1
			SET @TINHTRANG = N'Đã xác nhận'
			INSERT INTO PHIEUGUIHANG VALUES (@MA_PGUI,@MA_NCC,@MAKHO,@NGAYGUIDK,NULL,@TINHTRANG,NULL)
		END
		SELECT*FROM PHIEUGUIHANG WHERE MA_PGUI=@MA_PGUI
		PRINT N'Thêm phiếu gửi hàng thành công!'
	END
GO

--DELETE
CREATE PROC sp_DelPGH
	@MANV INT,
	@MATKHAU NVARCHAR(100),
	@MAKHO NVARCHAR(100),
	@YEUCAU NVARCHAR(100),
	@MAPGH INT,
	@MANCC INT
AS
BEGIN
	BEGIN TRAN
	BEGIN TRY
		IF (EXISTS (SELECT NV.MANV FROM NHANVIEN NV,KHO_NV KNV WHERE KNV.MANV = @MANV AND KNV.MANV=NV.MANV
			  AND NV.MATKHAU = @MATKHAU AND KNV.MAKHO = @MAKHO AND NV.CHUCVU = N'Quản lý kho'))
		BEGIN
			IF (EXISTS	(SELECT PGH.MA_PGUI FROM PHIEUGUIHANG PGH, NHACUNGCAP NCC 
			WHERE NCC.MA_NCC=PGH.MA_NCC AND PGH.MA_PGUI = @MAPGH AND @MANCC = NCC.MA_NCC))
			BEGIN
				IF @YEUCAU = N'HỦY PHIẾU GỞI HÀNG'
				BEGIN
					DELETE	PGH_MH WHERE @MAPGH = MA_PGUI
					DELETE PHIEUGUIHANG WHERE @MAPGH = MA_PGUI
					PRINT N'ĐƠN HÀNG ĐÃ ĐƯỢC HỦY THÀNH CÔNG!'
				END
			END
        END
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
		PRINT N'YÊU CẦU HỦY ĐƠN KHÔNG THÀNH CÔNG'
	END CATCH
END
EXEC sp_DelPGH @MANV = 1 ,
	@MATKHAU =124324321 ,
	@MAKHO  = 2,
	@YEUCAU = N'HỦY PHIẾU GỞI HÀNG',
	@MAPGH = 2 ,
	@MANCC = 1
GO

-- NHÂN VIÊN CẬP NHẬT TÌNH TRẠNG PHIẾU GỬI
CREATE PROC sp_InPGH_NV
	@MANV INT,
	@MATKHAU NVARCHAR(100),
	@MAKHO INT,
	@MA_PGUI INT,
	@NGAYNHAP DATE
AS
	DECLARE @NGAYGUIDK DATE=(SELECT NGAYGUIDK FROM dbo.PHIEUGUIHANG WHERE MA_PGUI = @MA_PGUI)
	BEGIN TRAN
	BEGIN TRY
		IF (EXISTS (SELECT NV.MANV FROM NHANVIEN NV,KHO_NV KNV WHERE KNV.MANV = @MANV AND KNV.MANV=NV.MANV
			  AND NV.MATKHAU = @MATKHAU AND KNV.MAKHO = @MAKHO AND NV.CHUCVU = N'Quản lý kho') )
		BEGIN
			IF (EXISTS (SELECT MA_PGUI FROM PHIEUGUIHANG WHERE MA_PGUI= @MA_PGUI AND MAKHO = @MAKHO))
			BEGIN
				IF (DATEDIFF(DAY,@NGAYGUIDK,@NGAYNHAP) <= 2)
				BEGIN
					UPDATE dbo.PHIEUGUIHANG SET NGAYNHAP = @NGAYNHAP, TINHTRANG = N'Đã nhập hàng' WHERE MA_PGUI = @MA_PGUI
				END	
				ELSE 
				BEGIN
					UPDATE dbo.PHIEUGUIHANG SET NGAYNHAP = @NGAYNHAP, TINHTRANG = N'Đã hủy' WHERE MA_PGUI = @MA_PGUI
				END
				PRINT N'Cập nhật thành công!'
			END
		END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT N'Lỗi!Cập nhật thất bại!'
	END CATCH
GO

-- NHÀ CUNG CẤP THÊM THÔNG TIN BẢNG PGH_MH
CREATE PROC sp_InPGH_MH
	@MA_PGUI INT,
	@MA_NCC INT,
	@MAMH INT,
	@NGAYXUAT DATE,
	@SL1MH INT
AS
	DECLARE @SOLUONGTONG INT
	IF((NOT EXISTS (SELECT MA_PGUI FROM PHIEUGUIHANG WHERE MA_PGUI=@MA_PGUI AND MA_NCC= @MA_NCC))
		OR (NOT EXISTS (SELECT MAMH FROM MH_NCC WHERE MA_NCC= @MA_NCC AND MAMH=@MAMH)))
		PRINT N'Lỗi!Thông tin đã nhập không chính xác!'
	ELSE
	BEGIN	
		IF(CAST((SELECT DATEDIFF(DAY,P.NGAYNHAP,@NGAYXUAT) FROM PHIEUGUIHANG P,PGH_MH PM,MATHANG MH WHERE @MA_PGUI=P.MA_PGUI AND MH.MAMH=@MAMH AND MH.LOAIHANG=N'Sách')AS INT)>45 
			OR CAST((SELECT DATEDIFF(DAY,P.NGAYNHAP,@NGAYXUAT) FROM PHIEUGUIHANG P,PGH_MH PM,MATHANG MH WHERE @MA_PGUI=P.MA_PGUI AND MH.MAMH=@MAMH AND MH.LOAIHANG!=N'Sách')AS INT)>30)
			PRINT N'Lỗi!Thời gian lưu trữ mặt hàng tại kho vượt mức quy định!'
		ELSE
		BEGIN
			IF (@SL1MH > (SELECT SOLUONG FROM MH_NCC WHERE MAMH = @MAMH AND MA_NCC= @MA_NCC))
				PRINT N'Lỗi!Số lượng mặt hàng hiện có không đủ cung cấp!'
			ELSE
			BEGIN
				INSERT INTO PGH_MH VALUES (@MA_PGUI,@MAMH,@SL1MH,@NGAYXUAT)
				SET @SOLUONGTONG = (SELECT SUM(SOLUONG) FROM PGH_MH WHERE MA_PGUI=@MA_PGUI)
				IF(@SOLUONGTONG<10 OR @SOLUONGTONG>1000)
					PRINT N'Lỗi!Số lượng tồn không đúng quy định!'
				ELSE
				BEGIN
					UPDATE dbo.PHIEUGUIHANG SET SLTON = @SOLUONGTONG WHERE MA_PGUI = @MA_PGUI
				END
			END	
		END
	END
GO

----------------------------------------------------------------NHÂN VIÊN----------------------------------------------------------------
/* NHÂN VIÊN */
--INSERT
CREATE PROC sp_InNHANVIEN @HOTEN NVARCHAR(100),@CHUCVU NVARCHAR(100),@MATKHAU NVARCHAR(100)
AS
BEGIN
DECLARE @MANV INT
SET @MANV = (SELECT MAX(MANV) FROM NHANVIEN)
BEGIN TRAN
	BEGIN TRY
		IF (@MANV IS NULL)
		BEGIN
			SET @MANV = 1
			INSERT INTO NHANVIEN VALUES (@MANV,@HOTEN,@CHUCVU,@MATKHAU)
		END	
		ELSE 
		BEGIN	
			SET @MANV = (SELECT MAX(MANV) FROM NHANVIEN) + 1 
			INSERT INTO NHANVIEN VALUES (@MANV,@HOTEN,@CHUCVU,@MATKHAU)
		END	
		COMMIT TRAN
		PRINT N'Thêm nhân viên thành công!'
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT N'Lỗi!Thêm nhân viên thất bại!'
	END CATCH
END
GO

--UPDATE
CREATE PROC sp_UpNHANVIEN @MANV INT,@HOTEN NVARCHAR(100),@CHUCVU NVARCHAR(100),@MATKHAU NVARCHAR(100)
AS
	IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV))
		PRINT N'Lỗi!Nhân viên không tồn tại!'
	ELSE
	BEGIN	
		UPDATE NHANVIEN SET HOTEN=@HOTEN,CHUCVU=@CHUCVU,MATKHAU=@MATKHAU WHERE MANV=@MANV
		SELECT*FROM NHANVIEN WHERE MANV=@MANV
	END	
GO

--DELETE
CREATE PROC sp_DelNVIEN @MANV INT
AS
	IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV))
		PRINT N'Lỗi!Nhân viên không tồn tại!'
	ELSE
	BEGIN
		DELETE FROM KHO_NV WHERE MANV=@MANV
		DELETE FROM NHANVIEN WHERE MANV=@MANV
		PRINT N'Xóa nhân viên thành công!'
	END
GO

/* THÀNH TÍCH NHÂN VIÊN */
--INSERT
CREATE PROC sp_InTTNV @MANV INT,@NAM INT,@SODON_HOANTHANH INT,@SO_REPORT INT
AS
	IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV))
		PRINT N'Lỗi!Nhân viên không tồn tại!'
	ELSE
	BEGIN
		IF(@SO_REPORT>=50 OR @SODON_HOANTHANH<=100)
			INSERT INTO THANHTICHNV VALUES(@MANV,@NAM,@SODON_HOANTHANH,@SO_REPORT,N'Kém')
		ELSE
		BEGIN
			IF((@SO_REPORT<50 AND @SO_REPORT>=35) OR (@SODON_HOANTHANH>100 AND @SODON_HOANTHANH<=300))
				INSERT INTO THANHTICHNV VALUES(@MANV,@NAM,@SODON_HOANTHANH,@SO_REPORT,N'Trung Bình')
			ELSE 
			BEGIN
				IF((@SO_REPORT<35 AND @SO_REPORT>=20) OR (@SODON_HOANTHANH>300 AND @SODON_HOANTHANH<=500))
					INSERT INTO THANHTICHNV VALUES(@MANV,@NAM,@SODON_HOANTHANH,@SO_REPORT,N'Khá')
				ELSE
				BEGIN
					IF((@SO_REPORT<20 AND @SO_REPORT>0) OR (@SODON_HOANTHANH>500 AND @SODON_HOANTHANH<=1500))
						INSERT INTO THANHTICHNV VALUES(@MANV,@NAM,@SODON_HOANTHANH,@SO_REPORT,N'Tốt')
					ELSE 
					BEGIN
						IF(@SO_REPORT=0 AND @SODON_HOANTHANH>1500)
							INSERT INTO THANHTICHNV VALUES(@MANV,@NAM,@SODON_HOANTHANH,@SO_REPORT,N'Xuất Sắc')
					END
				END
			END
		END
		SELECT*FROM THANHTICHNV WHERE MANV=@MANV
		PRINT N'Thêm thành tích nhân viên thành công!'
	END
GO
-- KHÔNG CHO PHÉP UPDATE VÀ DELETE


----------------------------------------------------------------MẶT HÀNG----------------------------------------------------------------
/* MẶT HÀNG */

--INSERT
CREATE PROC sp_InMH
	@TENMH NVARCHAR(100),
	@LOAIHANG NVARCHAR(100),
	@THUONGHIEU NVARCHAR(100),
	@GIATIEN FLOAT,
	@TGBAOHANH INT
AS
BEGIN	
DECLARE @MAMH INT
SET @MAMH = (SELECT MAX(MAMH) FROM MATHANG)
BEGIN TRAN 
	BEGIN TRY
		IF(@MAMH=NULL)
		BEGIN
			SET @MAMH=1
			INSERT INTO MATHANG VALUES(@MAMH,@TENMH,@LOAIHANG,@THUONGHIEU,@GIATIEN,@TGBAOHANH)
		END
		ELSE
		BEGIN
			SET @MAMH = @MAMH +1
			INSERT INTO MATHANG VALUES(@MAMH,@TENMH,@LOAIHANG,@THUONGHIEU,@GIATIEN,@TGBAOHANH)
		END
		COMMIT TRAN
		PRINT N'Thêm mặt hàng thành công!'
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT N'Lỗi!Thêm mặt hàng thất bại!'
	END CATCH
END 
GO

--UPDATE
CREATE PROC sp_UpMH 
	@MAMH INT,
	@TENMH NVARCHAR(100),
	@LOAIHANG NVARCHAR(100),
	@THUONGHIEU NVARCHAR(100),
	@GIATIEN FLOAT,
	@TGBAOHANH INT
AS
	IF(NOT EXISTS(SELECT MAMH FROM MATHANG WHERE MAMH=@MAMH))
		PRINT N'Lỗi!Mặt hàng không tồn tại!'
	ELSE
	BEGIN	
		UPDATE MATHANG SET TENMH=@TENMH,LOAIHANG=@LOAIHANG,THUONGHIEU=@THUONGHIEU,GIATIEN=@GIATIEN,TGBAOHANH=@TGBAOHANH WHERE MAMH=@MAMH
		SELECT*FROM MATHANG WHERE MAMH=@MAMH
		PRINT N'Cập nhật mặt hàng thành công!'
	END
GO

--DELETE
CREATE PROC sp_DelMH @MAMH INT
AS
	IF(NOT EXISTS(SELECT MAMH FROM MATHANG WHERE MAMH=@MAMH))
		PRINT N'Lỗi!Mặt hàng không tồn tại!'
	ELSE
	BEGIN
		DELETE FROM MH_NCC WHERE MAMH=@MAMH
		DELETE FROM MATHANG WHERE MAMH=@MAMH
		PRINT N'Xóa mặt hàng thành công!'
	END
GO
----------------------------------------------------------------MẶT HÀNG và NHÀ CUNG CẤP----------------------------------------------------------------
/* MH_NCC */
CREATE PROC sp_MHNCC @MAMH INT,@MA_NCC INT,@SL INT,@THAOTAC VARCHAR(100)
AS
	IF(NOT EXISTS(SELECT MAMH FROM MATHANG WHERE MAMH=@MAMH))
		PRINT N'Lỗi!Mặt hàng không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MA_NCC FROM NHACUNGCAP WHERE MA_NCC=@MA_NCC))
			PRINT N'Lỗi!Nhà cung cấp không tồn tại!'
		ELSE
		BEGIN
			IF(@THAOTAC='I')
			BEGIN
				INSERT INTO MH_NCC VALUES(@MAMH,@MA_NCC,@SL)
				SELECT*FROM MH_NCC
			END
			ELSE IF(@THAOTAC='D')
			BEGIN
				DELETE FROM MH_NCC WHERE MAMH=@MAMH AND MA_NCC=@MA_NCC
				SELECT*FROM MH_NCC
			END	
			ELSE IF(@THAOTAC='U')
			BEGIN	
				UPDATE MH_NCC SET SOLUONG = @SL WHERE MA_NCC=@MA_NCC AND MAMH=@MAMH
				SELECT*FROM MH_NCC WHERE MA_NCC=@MA_NCC AND MAMH=@MAMH
			END	
			ELSE
				PRINT N'Lỗi!Thao tác sai!'
		END
	END
GO

/* THỐNG KÊ MH */
--INSERT
CREATE PROC sp_InTKMH @MA_NCC INT,@MAMH INT,@NAMTK INT,@SL_BAN INT
AS
	IF(NOT EXISTS(SELECT MA_NCC FROM NHACUNGCAP WHERE MA_NCC=@MA_NCC))
		PRINT N'Lỗi!Nhà cung cấp không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MAMH FROM MATHANG WHERE MAMH=@MAMH))
			PRINT N'Lỗi!Mặt hàng không tồn tại!'
		ELSE
		BEGIN
			DECLARE @DOANHTHU FLOAT, @SL_TON INT
			SET @DOANHTHU = @SL_BAN*(SELECT GIATIEN FROM MATHANG WHERE MAMH=@MAMH)
			SET @SL_TON = (SELECT SOLUONG FROM MH_NCC WHERE MA_NCC= @MA_NCC AND MAMH= @MAMH) - @SL_BAN
			INSERT INTO THONGKEMH VALUES(@MA_NCC,@MAMH,@NAMTK,@SL_BAN,@SL_TON,@DOANHTHU)
			SELECT*FROM THONGKEMH
			PRINT N'Thống kê doanh thu mặt hàng thành công!'
		END
	END
GO
--KHÔNG CHO PHÉP UPDATE VÀ DELETE


----------------------------------------------------------------KHO----------------------------------------------------------------
/* KHO */
--INSERT
CREATE PROC sp_INKHO @DIACHI NVARCHAR(100),@SLCHUA INT
AS
	DECLARE @MAKHO INT
	SET @MAKHO =(SELECT MAX(MAKHO) FROM KHO)
	IF(@MAKHO IS NULL)
		SET @MAKHO=1
	ELSE
		SET @MAKHO=@MAKHO + 1
	INSERT INTO KHO VALUES(@MAKHO,@DIACHI,@SLCHUA)
	PRINT N'Thêm kho thành công!'
GO

-- UPDATE
CREATE PROC sp_UpKHO @MAKHO INT,@DIACHI NVARCHAR(100),@SLCHUA INT
AS
	IF(NOT EXISTS(SELECT MAKHO FROM KHO WHERE MAKHO=@MAKHO))
		PRINT N'Lỗi!Kho không tồn tại!'
	ELSE
	BEGIN
		UPDATE KHO SET DIACHI=@DIACHI,SLCHUA=@SLCHUA WHERE MAKHO=@MAKHO
		SELECT*FROM KHO WHERE MAKHO=@MAKHO
		PRINT N'Cập nhật kho thành công!'
	END
GO

--DELETE
CREATE PROC sp_DelKHO @MAKHO INT
AS
	IF(NOT EXISTS(SELECT MAKHO FROM KHO WHERE MAKHO=@MAKHO))
		PRINT N'Lỗi!Kho không tồn tại!'
	ELSE
	BEGIN
		DELETE FROM KHO_NV WHERE MAKHO=@MAKHO
		DELETE FROM KHO WHERE MAKHO=@MAKHO
		PRINT N'Xóa kho thành công!'
	END
GO

----------------------------------------------------------------KHO và NHÂN VIÊN----------------------------------------------------------------
/* KHO_NV */
--INSERT
CREATE PROC sp_InKHO_NV @MAKHO INT,@MANV INT
AS
	IF(NOT EXISTS(SELECT MAKHO FROM KHO WHERE MAKHO=@MAKHO))
		PRINT N'Lỗi!Kho không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV))
			PRINT N'Lỗi!Nhân viên không tồn tại!'
		ELSE
			IF (EXISTS (SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND (CHUCVU= N'Quản lý kho' OR CHUCVU= N'Giao hàng')))
			BEGIN
				INSERT INTO KHO_NV VALUES(@MAKHO,@MANV)
				PRINT N'Thêm thành công!'
			END
			ELSE
				PRINT N'Lỗi!Thêm thất bại!'
	END
GO

--UPDATE
CREATE PROC sp_UpKHO_NV @MAKHO INT,@MANV INT,@MANV2 INT
AS
	IF(NOT EXISTS(SELECT MAKHO FROM KHO WHERE MAKHO=@MAKHO))
		PRINT N'Lỗi!Kho không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV))
			PRINT N'Lỗi!Nhân viên không tồn tại!'
		ELSE
			IF (EXISTS (SELECT MANV FROM NHANVIEN WHERE MANV=@MANV2 AND (CHUCVU= N'Quản lý kho' OR CHUCVU= N'Giao hàng')))
			BEGIN
				UPDATE KHO_NV SET MANV=@MANV2 WHERE MAKHO=@MAKHO AND MANV=@MANV
				SELECT*FROM KHO_NV WHERE MAKHO=@MAKHO
				PRINT N'Cập nhật thành công!'
			END
			ELSE
				PRINT N'Lỗi!Cập nhật thất bại!'
	END
GO
--DELETE LÀM TRONG VS


----------------------------------------------------------------HÓA ĐƠN----------------------------------------------------------------
/* HOADON */
--INSERT
CREATE PROC sp_InHOADON 
	@MATK INT,
	@NGAYDAT DATE,
	@MAGG VARCHAR(100),
	@HUYDON BIT,
	@PTTT NVARCHAR(100),
	@STK VARCHAR(100)
AS
	IF(NOT EXISTS(SELECT MATK FROM TKKHACHHANG WHERE MATK=@MATK))
		PRINT N'Lỗi!Tài khoản không tồn tại!'
	ELSE
	BEGIN
		DECLARE @MAHD INT=(SELECT MAX(MAHD) FROM HOADON)
		IF(@MAHD IS NULL)
		BEGIN
			SET @MAHD=1
			INSERT INTO HOADON VALUES(@MAHD,@MATK,@NGAYDAT,@MAGG,N'Chờ xác nhận',@HUYDON,@PTTT,@STK,NULL)
		END
		ELSE
		BEGIN
			SET @MAHD=(SELECT MAX(MAHD) FROM HOADON)+1
			INSERT INTO HOADON VALUES(@MAHD,@MATK,@NGAYDAT,@MAGG,N'Chờ xác nhận',@HUYDON,@PTTT,@STK,NULL)
		END
		PRINT N'Thêm hóa đơn thành công!'
	END
GO

--UPDATE
CREATE PROC sp_UpHOADON @MANV INT,@MATKHAU NVARCHAR(100),@MAHD INT,@TINHTRANG NVARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
		IF(EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND CHUCVU=N'Quản lý hệ thống' AND MATKHAU=@MATKHAU))
		BEGIN
			IF (EXISTS (SELECT MAHD FROM HOADON WHERE MAHD = @MAHD))
			BEGIN
				IF(@TINHTRANG != N'Chờ xác nhận')
				BEGIN
					UPDATE HOADON SET TINHTRANG=@TINHTRANG WHERE MAHD=@MAHD
					IF(@TINHTRANG = N'Đã giao')
					BEGIN
						DECLARE @NGAYDAT DATE,@TONGTIEN FLOAT
						SET @NGAYDAT=(SELECT NGAYDAT FROM HOADON WHERE MAHD=@MAHD)
						SET @TONGTIEN=(SELECT SUM(THANHTIEN) FROM MH_HD WHERE MAHD=@MAHD)
						INSERT INTO LSDONHANG VALUES(@MAHD,@NGAYDAT,@TONGTIEN,@TINHTRANG)
					END
					SELECT*FROM HOADON WHERE MAHD=@MAHD
				END
			END
		END
		COMMIT TRAN
		PRINT N'Cập nhật hóa đơn thành công!'
	END TRY
	BEGIN CATCH
		ROLLBACK
		PRINT N'Lỗi!Cập nhật hóa đơn thất bại!'
	END CATCH
GO

--KHÁCH HÀNG ĐÁNH GIÁ HÓA ĐƠN
CREATE PROC sp_UpHOADONKH 
	@MATK INT,
	@MATKHAU NVARCHAR(100),
	@MAHD INT,
	@HUYDON BIT,
	@DANHGIA NVARCHAR(100)
AS
	IF(NOT EXISTS(SELECT MATK FROM TKKHACHHANG WHERE MATK=@MATK AND MATKHAU=@MATKHAU))
		PRINT N'Lỗi!Tài khoản không chính xác!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MAHD FROM HOADON WHERE MAHD=@MAHD AND MATK=@MATK))
			PRINT N'Lỗi!Hóa đơn không tồn tại!'
		ELSE
		BEGIN
			IF((SELECT TINHTRANG FROM HOADON WHERE MAHD=@MAHD AND MATK=@MATK)!=N'Đã giao')
				PRINT N'Lỗi!Chưa được đánh giá đơn hàng!'
			ELSE
				UPDATE HOADON SET DANHGIA=@DANHGIA WHERE MAHD=@MAHD
			IF(@HUYDON=1)
			BEGIN
				IF(((SELECT TINHTRANG FROM HOADON WHERE MAHD=@MAHD AND MATK=@MATK)!=N'Đã xác nhận')
					AND((SELECT TINHTRANG FROM HOADON WHERE MAHD=@MAHD AND MATK=@MATK)!=N'Chờ xác nhận'))
					PRINT N'Lỗi! Đã qua thời gian hủy đơn!'
				ELSE
					UPDATE HOADON SET HUYDON=@HUYDON WHERE MAHD=@MAHD
					UPDATE LSDONHANG SET TRANGTHAI=N'Hủy đơn' WHERE MAHD=@MAHD
			END
			ELSE 
			BEGIN
				IF(@HUYDON=0) 
					UPDATE HOADON SET HUYDON=@HUYDON WHERE MAHD=@MAHD
				ELSE
					PRINT N'Lỗi!Thao tác hủy đơn sai!'
			END
		END
	END
GO
--KHÔNG CHO PHÉP DELETE

/* PHIẾU BẢO HÀNH */
--INSERT
CREATE PROC sp_InPHIEUBAOHANH @MANV INT,@MATKHAU NVARCHAR(100),@MAHD INT,@MAMH INT,@NGAYBH DATE,@TINHTRANGMH NVARCHAR(100),@TINHTRANGBH NVARCHAR(100),@CHIPHI FLOAT
AS
	IF(NOT EXISTS(SELECT MAHD FROM HOADON WHERE MAHD=@MAHD))
		PRINT N'Lỗi!Hóa đơn không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MAMH FROM MATHANG WHERE MAMH=@MAMH))
			PRINT N'Lỗi!Mặt hàng không tồn tại!'
		ELSE
		BEGIN
			IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND CHUCVU=N'Quản lý hệ thống' AND MATKHAU=@MATKHAU))
				PRINT N'Lỗi!Nhân viên không hợp lệ!'
			ELSE
			BEGIN
				DECLARE @STT INT =(SELECT MAX(STT) FROM PHIEUBAOHANH)
				IF(@STT IS NULL)
					SET @STT=1
				ELSE
					SET @STT =(SELECT MAX(STT) FROM PHIEUBAOHANH)+1
				INSERT INTO PHIEUBAOHANH VALUES(@STT,@MAHD,@MAMH,@NGAYBH,@TINHTRANGMH,@TINHTRANGBH,@CHIPHI)
				PRINT N'Thêm phiếu bảo hành thành công!'
			END
		END
	END
GO

--UPDATE
CREATE PROC sp_UpPHIEUBAOHANH @MANV INT,@MATKHAU NVARCHAR(100),@MAHD INT,@MAMH INT,@TINHTRANGBH NVARCHAR(100)
AS
	IF(NOT EXISTS(SELECT MAHD FROM HOADON WHERE MAHD=@MAHD))
		PRINT N'Lỗi!Hóa đơn không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MAMH FROM MATHANG WHERE MAMH=@MAMH))
			PRINT N'Lỗi!Mặt hàng không tồn tại!'
		ELSE
		BEGIN
			IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND CHUCVU=N'Quản lý hệ thống' AND MATKHAU=@MATKHAU))
				PRINT N'Lỗi!Nhân viên không hợp lệ!'
			ELSE
			BEGIN
				UPDATE PHIEUBAOHANH SET TINHTRANGBH=@TINHTRANGBH WHERE MAHD=@MAHD AND MAMH=@MAMH
				SELECT*FROM PHIEUBAOHANH WHERE MAHD=@MAHD AND MAMH=@MAMH
				PRINT N'Cập nhật phiếu bảo hành thành công!'
			END
		END
	END
GO
--KHÔNG ĐƯỢC DELETE

/* PHIẾU TRẢ HÀNG */
--INSERT
CREATE PROC sp_InPHIEUTRAHANG @MANV INT,@MATKHAU NVARCHAR(100),@MAHD INT
AS
	IF(NOT EXISTS(SELECT MAHD FROM HOADON WHERE MAHD=@MAHD))
		PRINT N'Lỗi!Hóa đơn không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND CHUCVU=N'Quản lý hệ thống' AND MATKHAU=@MATKHAU))
			PRINT N'Lỗi!Nhân viên không hợp lệ!'
		ELSE
		BEGIN
			DECLARE @MA_PTRA INT,@NGAYTRA DATE
			SET @MA_PTRA = (SELECT MAX(MA_PTRA) FROM PHIEUTRAHANG)
			SET @NGAYTRA = (SELECT DATEADD(DAY,7,NGAYGIAO) FROM PHIEUGIAOHANG WHERE MAHD=@MAHD)
			IF(@MA_PTRA IS NULL)
			BEGIN
				SET @MA_PTRA=1
				INSERT INTO PHIEUTRAHANG VALUES(@MA_PTRA,@MAHD,@NGAYTRA)
			END
			ELSE
			BEGIN
				SET @MA_PTRA = (SELECT MAX(MA_PTRA) FROM PHIEUTRAHANG)+1
				INSERT INTO PHIEUTRAHANG VALUES(@MA_PTRA,@MAHD,@NGAYTRA)
			END
			PRINT N'Thêm phiếu trả hàng thành công!'
		END
	END
GO
--DELETE LÀM TRONG VS
--KHÔNG CHO PHÉP UPDATE

/* PHIẾU ĐỔI HÀNG */
--INSERT
CREATE PROC sp_InPHIEUDOIHANG @MANV INT,@MATKHAU NVARCHAR(100),@MAHD INT
AS
	IF(NOT EXISTS(SELECT MAHD FROM HOADON WHERE MAHD=@MAHD))
		PRINT N'Lỗi!Hóa đơn không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANV AND CHUCVU=N'Quản lý hệ thống' AND MATKHAU=@MATKHAU))
			PRINT N'Lỗi!Nhân viên không hợp lệ!'
		ELSE
		BEGIN
			DECLARE @MA_PDOI INT,@NGAYDOI DATE
			SET @MA_PDOI = (SELECT MAX(MA_PDOI) FROM PHIEUDOIHANG)
			SET @NGAYDOI = (SELECT DATEADD(DAY,7,NGAYGIAO) FROM PHIEUGIAOHANG WHERE MAHD=@MAHD)
			IF(@MA_PDOI IS NULL)
				SET @MA_PDOI=1
			ELSE
				SET @MA_PDOI = (SELECT MAX(MA_PDOI) FROM PHIEUDOIHANG)+1
			INSERT INTO PHIEUDOIHANG VALUES(@MA_PDOI,@MAHD,@NGAYDOI)
			PRINT N'Thêm phiếu đổi hàng thành công!'
		END
	END
GO
--DELETE LÀM TRONG VS
--KHÔNG CHO PHÉP UPDATE

/* PHIẾU GIAO HÀNG */
--INSERT 
CREATE PROC sp_InPHIEUGIAOHANG @MANVQL INT,@MATKHAU NVARCHAR(100),@MAHD INT,@MANV INT,@DIACHI NVARCHAR(100),@NGAYXUAT DATE
AS
	IF(NOT EXISTS(SELECT MAHD FROM HOADON WHERE MAHD=@MAHD))
		PRINT N'Lỗi!Hóa đơn không tồn tại!'
	ELSE
	BEGIN
		IF((SELECT CHUCVU FROM NHANVIEN WHERE MANV=@MANV)!=N'Giao hàng')
			PRINT N'Lỗi!Nhân viên được chọn không phải nhân viên giao hàng!'
		ELSE
		BEGIN
			IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANVQL AND CHUCVU=N'Quản lý hệ thống' AND MATKHAU=@MATKHAU))
				PRINT N'Lỗi!Nhân viên không hợp lệ!'
			ELSE
			BEGIN
				DECLARE @KHUVUC NVARCHAR(100),@CHIPHI FLOAT,@NGAYGIAO DATE,@MA_PGIAO INT
				SET @MA_PGIAO= (SELECT MAX(MA_PGIAO) FROM PHIEUGIAOHANG)
				IF((@DIACHI LIKE '%TP HCM')OR(@DIACHI LIKE '%Hà Nội')OR(@DIACHI LIKE '%Cần Thơ')OR(@DIACHI LIKE '%Đà Nẵng'))
				BEGIN
					SET @KHUVUC=N'Nội thành'
					SET @CHIPHI=20000
					SET @NGAYGIAO=DATEADD(DAY,3,@NGAYXUAT)
				END
				ELSE
				BEGIN
					SET @KHUVUC=N'Ngoại thành'
					SET @CHIPHI=35000
					SET @NGAYGIAO=DATEADD(DAY,7,@NGAYXUAT)
				END
				IF(@MA_PGIAO IS NULL)
					SET @MA_PGIAO=1
				ELSE
					SET @MA_PGIAO= (SELECT MAX(MA_PGIAO) FROM PHIEUGIAOHANG)+1
				INSERT INTO PHIEUGIAOHANG VALUES (@MA_PGIAO,@MAHD,@MANV,@KHUVUC,@DIACHI,@NGAYXUAT,@NGAYGIAO,@CHIPHI)
				PRINT N'Thêm phiếu giao hàng thành công!'
			END
		END
	END
GO

--UPDATE
CREATE PROC sp_UpPHIEUGIAOHANG @MANVQL INT,@MATKHAU NVARCHAR(100),@MA_PGIAO INT,@MANV INT
AS
	IF(NOT EXISTS(SELECT MA_PGIAO FROM PHIEUGIAOHANG WHERE MA_PGIAO=@MA_PGIAO))
		PRINT N'Lỗi!Phiếu giao hàng không tồn tại!'
	ELSE
	BEGIN
		IF((SELECT CHUCVU FROM NHANVIEN WHERE MANV=@MANV)!=N'Giao hàng')
			PRINT N'Lỗi!Nhân viên được chọn không phải nhân viên giao hàng!'
		ELSE
		BEGIN
			IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANVQL AND CHUCVU=N'Quản lý hệ thống' AND MATKHAU=@MATKHAU))
				RETURN 0
			ELSE
			BEGIN
				UPDATE PHIEUGIAOHANG SET MANV=@MANV WHERE MA_PGIAO=@MA_PGIAO
				SELECT*FROM PHIEUGIAOHANG WHERE MA_PGIAO=@MA_PGIAO
				PRINT N'Cập nhật phiếu giao hàng thành công!'
			END	
		END
	END
GO
--DELETE LÀM TRONG VS



----------------------------------------------------------------TÀI KHOẢN và MẶT HÀNG----------------------------------------------------------------
/* TK_MH */
--INSERT
CREATE PROC sp_InTK_MH @MATK INT,@MAMH INT,@MA_NCC INT,@SL INT
AS
	IF(NOT EXISTS(SELECT MATK FROM TKKHACHHANG WHERE MATK=@MATK))
		PRINT N'Lỗi!Tài khoản không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MAMH FROM MATHANG WHERE MAMH=@MAMH))
			PRINT N'Lỗi!Mặt hàng không tồn tại!'
		ELSE
		BEGIN
			IF(NOT EXISTS(SELECT MA_NCC FROM NHACUNGCAP WHERE MA_NCC=@MA_NCC))
				PRINT N'Nhà cung cấp không tồn tại!'
			ELSE
			BEGIN
				INSERT INTO TK_MH VALUES(@MATK,@MAMH,@MA_NCC,@SL)
				PRINT N'Thêm thành công!'
			END
		END
	END
GO

--UPDATE
CREATE PROC sp_UpTK_MH @MATK INT,@MAMH INT,@MA_NCC INT,@SL INT 
AS
	IF(NOT EXISTS(SELECT MATK FROM TKKHACHHANG WHERE MATK=@MATK))
		PRINT N'Lỗi!Tài khoản không tồn tại!'
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MAMH FROM MATHANG WHERE MAMH=@MAMH))
			PRINT N'Lỗi!Mặt hàng không tồn tại!'
		ELSE
		BEGIN
			IF(NOT EXISTS(SELECT MA_NCC FROM NHACUNGCAP WHERE MA_NCC=@MA_NCC))
				PRINT N'Lỗi!Nhà cung cấp không tồn tại!'
			ELSE
			BEGIN
			    SET @SL = @SL + (SELECT SL FROM TK_MH WHERE @MATK=@MATK AND MAMH=@MAMH AND MA_NCC=@MA_NCC) 
				UPDATE TK_MH SET SL=@SL WHERE @MATK=@MATK AND MAMH=@MAMH AND MA_NCC=@MA_NCC
				SELECT*FROM TK_MH WHERE @MATK=@MATK AND MAMH=@MAMH AND MA_NCC=@MA_NCC
				PRINT N'Cập nhật thành công!'
			END	
		END
	END
GO

--CHUYỂN MẶT HÀNG TỪ TK_MH SANG MH_HD
CREATE PROC sp_Trans_MH @MATK INT,@MAHD INT
AS
	IF(NOT EXISTS(SELECT MATK FROM TK_MH WHERE MATK=@MATK))
		RETURN 0
	ELSE
	BEGIN
		IF(NOT EXISTS(SELECT MAHD FROM HOADON WHERE MAHD=@MAHD))
			RETURN 0
		ELSE
		BEGIN
			INSERT INTO MH_HD (MAHD,MAMH,MA_NCC,SL) SELECT H.MAHD,TM.MAMH,TM.MA_NCC,TM.SL FROM TK_MH TM,HOADON H
			WHERE TM.MATK=H.MATK AND H.MATK=@MATK AND H.MAHD=@MAHD
			DELETE FROM TK_MH WHERE MATK=@MATK
		END
	END
GO

/* 1.	Đăng ký hoặc đăng nhập vào hệ thống ứng dụng */
----------------------------------------
----------- đăng ký tài khoản có ràng buộc tên tài khoản không được trùng nhau-----------

CREATE procedure DangKiTaiKhoan
	@HOTEN NVARCHAR(100),
	@GIOITINH NVARCHAR(10),
	@NGAYSINH DATE,
	@EMAIL NVARCHAR(100),
	@TENTK NVARCHAR(100),
	@MATKHAU NVARCHAR(100),
	@DIACHI NVARCHAR(100),
	@PHUONG NVARCHAR(100),
	@QUAN_HUYEN NVARCHAR(100),
	@TINH_TP NVARCHAR(100)
AS
	declare @MaTK int
	set @MaTK = (select max(MATK) from TKKHACHHANG)
	if(exists(select * from TKKHACHHANG where TENTK=@TENTK)) /*ràng buộc tên tài khoản không được trùng */
	     begin
		  rollback
		 end
	else
	     begin
		     if(@MaTK is null)
                  begin
			          set @MaTK=1;
		          end
	         else
	              begin
			          set @MaTK=@MaTK +1;
				  end
			 insert into TKKHACHHANG values (@MaTK,@HOTEN,@GIOITINH,@NGAYSINH,@EMAIL,@TENTK,@MATKHAU)
             insert into DIACHIKH values (@MaTK,@DIACHI,@PHUONG,@QUAN_HUYEN,@TINH_TP)
	      end
-------------------------------------------------TÀI KHOẢN KHÁCH HÀNG----------------------------------------------------
--CẬP NHẬT LẠI THÔNG TIN CỦA KHÁCH HÀNG
CREATE PROC CAPNHAT_TKKH 
	@TENTK NVARCHAR(100),
	@HOTEN NVARCHAR(100),
	@GIOITINH NVARCHAR(100),
	@NGAYSINH DATE,
	@EMAIL NVARCHAR(100),
	@DIACHI NVARCHAR(100),
	@PHUONG NVARCHAR(100),
	@QUAN_HUYEN NVARCHAR(100),
	@TINH_TP NVARCHAR(100)
AS
BEGIN
	DECLARE @MATK INT
	SET @MATK=(SELECT MATK from TKKHACHHANG where TENTK=@TENTK)
	BEGIN TRAN
		BEGIN TRY
			UPDATE TKKHACHHANG SET HOTEN=@HOTEN,GIOITINH=@GIOITINH,NGAYSINH=@NGAYSINH,EMAIL=@EMAIL WHERE MATK=@MATK
			UPDATE DIACHIKH SET DIACHI=@DIACHI,PHUONG=@PHUONG,QUAN_HUYEN=@QUAN_HUYEN,TINH_TP=@TINH_TP WHERE MATK=@MATK
			COMMIT TRAN
		END TRY
	BEGIN CATCH
		ROLLBACK
	END CATCH
END
-------------------cập nhật pass
create proc UPDATE_PASS @TENTK nvarchar(100),@pass nvarchar(100)
AS
	update TKKHACHHANG SET MATKHAU=@pass where TENTK=@TENTK

-------------------------------------- THÀNH LẬP HOÁ ĐƠN-----------------------------------------
-- THÀNH LẬP HOÁ ĐƠN

CREATE proc THANHLAPHOADON @TENTK nvarchar(100)
AS
	DECLARE @MAHD INT
	declare @MATK int
	set @MATK=(select MATK from TKKHACHHANG where TENTK=@TENTK)
	SET @MAHD=(SELECT MAX(MAHD) FROM HOADON)
	IF(@MAHD is null)
	BEGIN
		SET @MAHD=1;
	END
	ELSE
	BEGIN
		SET @MAHD=@MAHD+1
	end
	INSERT INTO HOADON VALUES (@MAHD,@MATK,NULL,NULL,N'Chờ xác nhận',NULL,NULL,NULL,NULL,NULL)
	---------SAU KHI THÀNH LẬP HOÁ ĐƠN THÌ THÊM VÀO BẢNG HD_MH
	declare @n int--mamh
	set @n=(SELECT MAX(MAMH) FROM TK_MH WHERE MATK=@MATK)
	declare @m int--ma_ncc
	set @m=(SELECT MAX(MA_NCC) FROM TK_MH WHERE MATK=@MATK)
	declare @temp int
	set @temp=@n
	while(@m!=0)
	begin
		while(@n!=0)
		begin
			if(exists(select* from TK_MH where MATK=@MATK and MAMH=@n and MA_NCC=@m))
		    begin
				declare @sl int
				set @sl=(select SL from TK_MH where MATK=@MATK AND MAMH=@n AND MA_NCC=@m)
				insert into MH_HD VALUES (@MAHD,@n,@m,@sl,null,null)
				delete TK_MH where MATK=@MATK and MAMH=@n and MA_NCC=@m
			end
			set @n=@n-1
		 end
	set @n=@temp
	set @m=@m-1
	end

 select* from TK_MH
 exec THANHLAPHOADON N'NTNH'
 
 ----------- --------------UPDEATE GIỎ HÀNG
CREATE PROC UPDATE_GIOHANG @TENTK NVARCHAR(100),@MAMH INT,@MANCC INT,@SL INT
AS
	DECLARE @MATK INT
	SET @MATK =(SELECT MATK FROM TKKHACHHANG WHERE TENTK=@TENTK)
	UPDATE TK_MH SET SL=@SL WHERE MATK=@MATK AND MAMH=@MAMH AND MA_NCC=@MANCC

------------------------------------------------------------------------------
-------------------------------

create PROC INSERT_GIOHANG @TENTK NVARCHAR(100),@MAMH INT,@MANCC INT,@SL INT
AS
  declare @MATK int
  set @MATK= (SELECT MATK from TKKHACHHANG where TENTK=@TENTK)
  IF(EXISTS(SELECT*FROM dbo.TK_MH WHERE MAMH=@MAMH AND MA_NCC=@MANCC AND MATK=@MATK))
  BEGIN
     SET @SL=@SL+(SELECT SL FROM dbo.TK_MH WHERE MAMH=@MAMH AND MA_NCC=@MANCC AND MATK=@MATK)
     UPDATE TK_MH SET SL=@SL WHERE MATK=@MATK AND MAMH=@MAMH AND MA_NCC=@MANCC
  END
  ELSE
  BEGIN
     INSERT INTO TK_MH VALUES(@MATK,@MAMH,@MANCC,@SL)
  END

------------------------------------------------------------
--------------- store này để hiển thị thông tin giỏ hàng
create proc VIEW_GIOHANG @TENTK nvarchar(100)
as
   DECLARE @MATK INT
   SET @MATK=(SELECT MATK from TKKHACHHANG WHERE TENTK=@TENTK)
   SELECT MH.MAMH,NCC.MA_NCC,MH.TENMH, NCC.TEN_NCC,MH.THUONGHIEU,MH.GIATIEN,TK_MH.SL FROM MATHANG MH,NHACUNGCAP NCC, TK_MH
   WHERE MATK=@MATK AND TK_MH.MA_NCC=NCC.MA_NCC AND MH.MAMH=TK_MH.MAMH

---------------------------------------------------------------
create proc XOA_GIOHANG @TENTK NVARCHAR(100),@MAMH INT,@MANCC INT
AS
	DECLARE @MATK INT
	SET @MATK =(SELECT MATK FROM TKKHACHHANG WHERE TENTK=@TENTK)
	DELETE TK_MH WHERE MATK=@MATK AND MAMH=@MAMH AND MA_NCC=@MANCC

---------dùng để huỳ hoá đơn trong vs
CREATE PROC HUYHD @MAHD INT
AS
	update HOADON SET TINHTRANG=N'Đã huỷ',HUYDON=1  where MAHD=@MAHD

-----------test
SELECT * FROM TK_MH
exec THANHLAPHOADON N'NTNH'
SELECT MAX(MA_NCC) FROM TK_MH WHERE MATK=1
select *from MH_HD
select * from HOADON

